### ISSUE TITLE
Progress Meter/Analysis Tool/Visualization

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/overview#1]
We need better ways for volunteers to identify relevant areas of the target websites.  Primers provided to us from the policy analysis group will be really helpful. But it might also be really useful to hook up the [sitemap tool](https://github.com/guerrilla-archiving/epa) to the records of what's already been nominated, so we have some kind of visualization of what's already been done & where we have extensive needs.

**Comment by geppy** [comment]
I agree.  Depending on the way the sitemap is presented, it may make sense to use annotations (as with [hypothes.is](https://hypothes.is) and/or the upcoming [Web Annotation spec](https://www.w3.org/annotation/)) or it may make sense to use some sort of URL-matching DSL.

**Comment by dcwalk** [comment]
@titaniumbones I feel like this is getting addressed in the pipeline app. Would it be alright if I closed this issue? Will do so if I don't get a response in the next couple days

**Comment by dcwalk** [comment]
Closed, considering this an issue to raise directly in `pipeline`
