### ISSUE TITLE
Discussion on Content Moderation

### ISSUE THREAD

**Issue by ChaiBapchya** [edgi-govdata-archiving/overview#106]
While searching for tools similar to _Versionista_, this is what I found. I stumbled across a different (from **Tracking / Monitoring changes**) yet (I think a bit relevant) term - **Content Moderation**

As we talk about meaningful changes, tracking changes, finding diffs and prioritizing them, one of my searches led me to AWS Marketplace products such as WebPurify Image Moderation, etc which moderate web content / traffic.

Drawing analogy to our use-case, all we are doing is actually moderating the changes.
Under this ambit, also include - 

1. [Smart Moderation](https://www.smartmoderation.com/)
Based on ML, NLP + self-learning like Human 
[API Documentation](http://api.smartmoderation.com/v2.0/docs#analyze)

2. [Implio](http://www.implio.com/)
Automated (ML based) + Manual content moderation + Ability to write filters
[Choosing between ML Generic/Custom-made and Filters](http://www.implio.com/blog/which-automation-is-right-for-you/)

3. [IOSquare](http://iosquare.com/content_moderation.php)
[Monitoring](http://iosquare.com/io_monitor.php), Automated Analysis and Visualization
IoSquare merged with Besedo

### **_On the flipside_**

[Why automation can never replace human-content-moderation! ](https://www.openaccessbpo.com/blog/automation-can-never-replace-human-content-moderation)
It talks about how human intervention is critical when it comes to :- 

- **context-awareness**
- **Subjectivity to detect subtle references used**
- **Cultural references, colloquialisms, and racial slurs** 

What do you make of this @dcwalk @b5 @danielballan ? Have you heard about it before? Do you find this of any use? Anything worth picking up / learning from?

**Comment by danielballan** [comment]
Yes, I think there's a useful analogy here.

**Comment by danielballan** [comment]
Having just caught up on https://github.com/edgi-govdata-archiving/web-monitoring-processing/issues/28 it looks like there are strongly analogies in other prior art, like analyzing Wikipedia edit history.

**Comment by dcwalk** [comment]
Awesome, I agree with @danielballan that there are strong analogies to this and monitoring and it seems like we should definitely be paying attention to how projects are working on moderation to help us think through features of our web monitoring system! 

We tend to use the issues in this "overview" repo for meta-organizing across all our projects, but as I interpret this as being about the web monitoring project directly, it likely belongs in there. Are you able to move this issue to https://github.com/edgi-govdata-archiving/web-monitoring @ChaiBapchya ?

**Comment by ChaiBapchya** [comment]
I'm glad this finding is relevant and useful.

Alright sure. Will move it to web-monitoring. @dcwalk

**Comment by ChaiBapchya** [comment]
This issue was moved to edgi-govdata-archiving/web-monitoring#29

**Comment by titaniumbones** [comment]
@danielballan @ChaiBapchya does anyone on this thread actually know where the wikipedia content moderation code is?
