### ISSUE TITLE
Rename repos and add descriptions

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/overview#12]
Just noticing we have a lot of tool names and descriptions that are not clear, especially for the ones that are tailored to specific agency.

I'd suggest:
- [x] consistently rename repos to link to specific datasets/agencies 
- [x] update repo descriptions to make clear status and outcomes of tool

**Comment by titaniumbones** [comment]
This is important, if you don't get to it tonight I'll try to start on it after my meeting (10ish, though I collapse around 10:30...)

**Comment by dcwalk** [comment]
I'll work on this now, ping me if/when you have time tonight!
