### ISSUE TITLE
Where's the data?

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/overview#121]
We're often asked this question, and we often have a very hard time answering, because the "data" might be in any of several places. We should incrementally improve our capacity to answer this question, with:

- [x] a web page that gives a frank answer (look in CKAN, look in IA, look in archivers 1, look in archivers 2, look in azimuth, etc.)
- ~a search form or chatbot that executes most of those searches for the user~
- [x] an interface in archivers 2 that does the same work 

cf. https://github.com/edgi-govdata-archiving/overview/issues/120

**Comment by dcwalk** [comment]
Hey @shaqsingh-- would love to fold your visualization work into addressing these concerns. Maybe writing some of those notes about places could happen as you pull together stats?

**Comment by dcwalk** [comment]
Update on this:

- The "Archiving" EDGI page reflects part of this: https://envirodatagov.org/archiving/
- We have a nascent way to visualize the "coverage" in: https://alpha.archivers.space/coverage

**Comment by dcwalk** [comment]
Really got to think about improving the way people could unpack this answer -- @shaqsingh and @patcon  would love to discuss tomorrow!

**Comment by dcwalk** [comment]
I'm going to close this issue for now, as I think we've updated this on our website. 

The last idea: of a search/chatbot is awesome, but out of scope and so deserves its own issue, reticketed: #175!
