### ISSUE TITLE
Update Github owners and lieutenants

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/overview#122]
Related to #75, we have had some members of the project become inactive over the last while, who are still listed as *Owners* and *Lieutenants,* I'd like to revisit and update these groups to reflect those currently active

@edgi-govdata-archiving/lieutenants could you all respond here by **April 30** if you are still interested in serving in a pull review, admin and/or maintainer capacity?

Thanks!

**Comment by sonalranjit** [comment]
interested

**Comment by b5** [comment]
well, if @sonalranjit's interested, consider me interested.

**Comment by wdenton** [comment]
You can drop me.

**Comment by louh** [comment]
I haven't had time to keep up, unfortunately :(

**Comment by mi-lee** [comment]
Sure, I'd be interested, although I've had limited experience with the rest of the repos.

**Comment by ebarry** [comment]
I'm still around.

**Comment by shabscan** [comment]
Interested

**Comment by kmcculloch** [comment]
I've been AWOL but haven't lost interest in being involved.

**Comment by shapironick** [comment]
I'm still here but don't need to be a lieutenant or an owner as I don't do my EDGI work on github. It's just a remainder from the early days 

Sent on the move

**Comment by murphyofglad** [comment]
Hi all
I am still here! 
Michelle

**Comment by dcwalk** [comment]
Thanks all who responded, permissions updated :)
