### ISSUE TITLE
Register EDGI project for Mozilla Global Sprints on Jun 1-2, 2017

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/overview#127]
From May 11 Community Call (and Slack):

I’d love for us to get something scoped and ready for Mozilla’s Global Sprint on June 1-2: https://mozilla.github.io/global-sprint
A couple possibilities that were mentioned:
1. Diffing services for Web Monitoring
2. All of Web Monitoring
3. Writing scraper scripts (this one likely requires more up front work to get us ready in time)

[**Project Requirements**](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) we will need to meet to be "featured"

TODOs:
We should participate in the Jun 1-2 Mozilla Global Sprint, details: https://mozilla.github.io/global-sprint/project-lead/project-requirements/

TODOs:
- [x] complete registration
- [x] take the Open Leadership 101 training 
- [x] ensure we are listed as a featured project
- [x] advertise/send out emails
  - [x] Civic Tech TO (@patcon @titaniumbones)
  - [x] EDGI and Archivers Slacks
  - [x] GA FB page (michelle)
  - [x] GA email list

**Comment by dcwalk** [comment]
PRs merged in!

- [x] We just have to mark as "Ready to Launch" with mozfest: https://github.com/mozilla/global-sprint/issues/102

**Comment by dcwalk** [comment]
@patcon and @titaniumbones can you announce the Global Sprint participation at CivicTechTO on tuesday?

**Comment by dcwalk** [comment]
Also spoke with @titaniumbones and Michelle about sending out to the facebook page or any Toronto event attendees

**Comment by titaniumbones** [comment]
For sure. 

On May 29, 2017 11:22:51 AM EDT, dcwalk <notifications@github.com> wrote:
>@patcon and @titaniumbones can you announce the Global Sprint
>participation at CivicTechTO on tuesday?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/edgi-govdata-archiving/overview/issues/127#issuecomment-304686032

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dcwalk** [comment]
Marking this as closed-- we've done all we can :)
