### ISSUE TITLE
Create Awesome lists for our tool tracking needs

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/overview#130]
I've been trying to understand the tool landscape for EDGI the organization (ie. admin tools like Zoom, Hangouts, etc.), as well as the landscapes of web page diffing and web page archiving. In some ways they differ, but in many ways all these tools are part of the same high-level wondering -- what do we know about? what do we use? what has already been discussed?

We have a few approaches:

- tracking in **GitHub issues** like edgi-govdata-archiving/web-monitoring#18
- tracking in **Trello boards** (personal effort). I added the tools to [my own board](https://trello.com/b/fCW9rjAL/archivers-tools?menu=filter&filter=label:Change%20Monitoring) fwiw.
- tracking in **google spreadsheets** like we do with [web archiving tools](https://docs.google.com/spreadsheets/d/1FqxwaZnIhhQ7jDCC-W64NMRf5rDeh2Shx3u01MsBmTQ/edit#gid=0). (Yay @mhucka!)

The above are all things we're maintaining ourselves.

One other approach I'm aware of is:

- [awesome lists](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Awesome lists are a thing that started a few years ago to help developers easily track projects and services as they became overwhelmed. Like I can google "awesome list scraping" some existing lists:

- https://github.com/duyetdev/awesome-web-scraper
- https://github.com/lorien/awesome-web-scraping
- https://github.com/BruceDone/awesome-crawler
- https://github.com/Kikobeats/awesome-scraping

They're nothing fancy, but pretty much just a [schelling point](https://en.wikipedia.org/wiki/Focal_point_(game_theory)) for technical folks to build shared resources.

The main perk of these is that they can be community-maintained. We could create `edgi-govdata-archiving/wesome-web-diffing` and `edgi-govdata-archiving/awesome-web-archiving` and then poke all these related projects and say "hey, you're maintaining a little section of your README for related projects, but how about you just link to us, and we'll add you as a co-maintainer"

That's an interesting hook to engage with communities working in our space (yay, potential future collabs!), plus it means our resources are less likely to rot.

So here's my suggestion:

1. We decided on the scope of one or two awesome lists
2. We create them, with loose details.
3. We link those to our internal read-only spreadsheet (because yay sharing) for the sort of deep detail we're keeping in those.
4. We poke projects about linking our awesome lists, and offer commit access and co-maintainership.

Benefits:
- more engagement with related communities
- more outside help maintaining docs

**Comment by dcwalk** [comment]
Hey @patcon just wanted to check in on this... it seems like with the joint iipc list for web archiving that awesome list is probably something we want to merge with.

Revisiting this issue however, I feel like there are 2 different things you are addressing here. The first half being far more about onboarding. Do the current round of trello onboarding experiments obviate the need for a seperate trello tool list? Does our current EDGI protocol, which documents "online edgi spaces" also kind of eat away at the original need?

Can you provide an update? As I'm interpreting this now it might make sense to mark as `wontdo`?

**Comment by patcon** [comment]
You're totally right that the mentioning above of both the spreadsheet/awesomelist and the trello board was conflating purposes.

1. spreadsheet/awesomelist: things we're aware of (perhaps no intention to ever use)
2. trello: for communicating tools we're investigating/using/abandonning

> Do the current round of trello onboarding experiments obviate the need for a seperate trello tool list?

I think they could go a long way to helping with tool confusion -- as in, if we use a tool, it should be explained in onboarding.

> Does our current EDGI protocol, which documents "online edgi spaces" also kind of eat away at the original need?

I love the EDGI Protocol, but I feel it's a doc with a necessary entry barrier (ie. things shouldn't be added there unless quite established), and quite dense (though it's explicitness is important!)

I feel if a Trello tool board has any value, it would be these aspects: 
1. **Skimmable.** Even if lots of context around a tool/process/practice, that thing still takes the space of a single card among many.
1. **Directional.** (coming in or going out is easier to see: e.g. Data Rescue Workflow, etc.)
1. **Low barrier to edit.** A place that things could go early, even if only one person were trialing it.
1. **Fluid.** I feel that trello cards convey themselves as "blocks to be moved around", unlike documents which sometimes convey "content to be consumed". That's a little subjective, though :)

But having said all that, I don't think I have space to tend to a trello tool board. Just wanted to commit the thinking somewhere
