### ISSUE TITLE
Document project deployments and map services

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/overview#135]
Related to #134, this is a tracking issue for an ongoing conversation in `#handling_keys` on EDGI slack.

@dcwalk's summary of issue:
> 1. We have accts that we need to share credentials between a small group of people
> 2. We need a better way to coordinate sharing of keys and sensitive details between individuals
> 3. We are getting to the point where we will need to better document deployment or other semi-sensitive details within a small group of developers
> 4. Organizational context is one where we shouldn’t count on regular sysadmin support (e.g. maintaining our own servers for docs or cred management)

Also see https://github.com/edgi-govdata-archiving/web-monitoring-db/issues/50

TODO:
- [x] ✅ each service verified
- ~web monitoring deployment documented~
- ~archivers.space deployment documented~

**Comment by dcwalk** [comment]
We've set up a prelim version using Dropbox Paper and will be trialing it over the next few months. Thanks @patcon for kicking off the services documenting, we are still aways out...

**Comment by patcon** [comment]
https://paper.dropbox.com/doc/Services-Deployment-pTsHUVIb2JuFHo8KVfpq2

**Comment by dcwalk** [comment]
I've run through and tried to confirm details, add notes in the doc. I think a little be more kicking the ball down the course and we'll have verified what services we're using!

**Comment by dcwalk** [comment]
I've done another pass, we decided to defer documenting web monitoring deployment until Fall, so I'm going to reticket that as #176 and add to our Fall Milestone (beginning)!
