### ISSUE TITLE
Do Post Mozilla Sprint Cleanup

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/overview#138]
I'll assume we've rocked it (we're awesome 🥀 )

A couple TODOs come to mind:
- [x] undo the following documentation PRs:
  - #136
  - https://github.com/edgi-govdata-archiving/web-monitoring/pull/33
  - https://github.com/edgi-govdata-archiving/web-monitoring-processing/pull/43
- [x] _perhaps_ write a blog post celebrating our accomplishments? 🎉

**Comment by dcwalk** [comment]
(blocked until after the event 😁 )

**Comment by titaniumbones** [comment]
We ended up changing the README's several times... so it seemed like less work to push new commits rather than undoing the ones you'd pointed to.  And I've written a version of the blog post, so I think I'll close this up!
