### ISSUE TITLE
Deploy halpy bot on Archivers slack

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/overview#139]
It's hard to depend on chatbot features that only exist in 1/2 the chat space.

I think we can create a new heroku app hosting another bot, but have them both share the same redis brain. This will keep some of the nice features in sync, and shouldn't have negative consequences.

### Caveats

- if the per-channel rss notifier is used in a channel on one slack that is also present on another, it might confuse the chatbot. This isn't currently an issue.

**Comment by dcwalk** [comment]
Just want to link this to convo in https://github.com/edgi-govdata-archiving/edgi-hubot/issues/17 about delaying deployment. Seems like with bridging work this might be less urgent.

**Comment by dcwalk** [comment]
ping @patcon is this something we can close as `wontdo`?

**Comment by patcon** [comment]
Making as `wontdo` pending https://github.com/edgi-govdata-archiving/edgi-hubot/issues/17#issuecomment-313881100

h/t @dcwalk
