### ISSUE TITLE
Contribute to Data Together visioning docs

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/overview#144]
As a founding partner in Data Together, EDGI should contribute for formulating the vision for the project.

**Comment by dcwalk** [comment]
Just an update that this has been ongoing, with a tentative mid-July deadline for the first vision docs

**Comment by dcwalk** [comment]
The Data Together site is up! http://datatogether.org/
@flyingzumwalt is looking at the final steps to get this over the line.

**Comment by dcwalk** [comment]
We held another vision doc session on Aug 25, with the takeaway that we'll aim to share some individual work and tighten together from there (with asking for more feedback from emerging partners) by Aug 27 and Aug 29

**Comment by dcwalk** [comment]
Here is the issue on Data Together for tracking this: https://github.com/datatogether/datatogether/issues/13

**Comment by dcwalk** [comment]
I'm gonna say we've done that! Our drafts are in, we've participated throughout the process, and things are moving toward the next step :3
