### ISSUE TITLE
Reach out to other web-archiving projects about collab on our tool comparison resource

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/overview#145]
@mhucka has gone to great efforts to create an comparison resource:
https://github.com/archivers-space/research/tree/master/web_archiving

It would be great if we could lure other FOSS projects into collaborating on this with us on this :)

One way to do this might be to write some boilerplate copy for how this would fit into a README (perhaps copying that into the research README), and then open issues (or even pull requests?) in the various projects, asking how they'd feel about linking to it.

We'd also probably want to immediately give that maintainer access to work on that research repo, so that they don't suffer inconvenience beyond what they'd have maintaining their own. We might need a new GitHub team for this, so if you go that route, you might need to collaborate with @patcon @dcwalk @b5 or @lizbarry [or others on this page](https://github.com/orgs/archivers-space/people) to ensure they're added to an appropriate team :)

Something like this, but please improve lingo!
https://github.com/archivers-space/sentry/pull/6

**Comment by dcwalk** [comment]
Post-IIPC I think we want to actually start contributing what we know to their [Awesome Web Archiving](https://github.com/iipc/awesome-web-archiving) list.

Great minds 😂

**Comment by mhucka** [comment]
That awesome list seems to have been started on June 16. Was it literally the result of a discussion during IIPC? If so, were you there by any chance, and do you know more background?

**Comment by dcwalk** [comment]
Yeah it was @mhucka, tho to my understanding there was a previous list hosted on the IIPC site. I think the context was just that there is a lack of current resources to let new people to web archiving, and also people in specific areas, to understand the breadth of web archiving tools.

**Comment by dcwalk** [comment]
Hey -- I feel like you are getting this ball rolling @patcon :) 
It seems to me like maybe this could be closed when you feel ready? As it is sort of moving out of a `first-timer` task?

**Comment by dcwalk** [comment]
ping @patcon -- I think this has happened (and we've seen some initial fruits of that outreach!)

Unless I hear otherwise I'm going to close this issue as done after 48 hours so say by Thurs, July 20 (and specific future plans can be ticketed out)?
