### ISSUE TITLE
Office Hours/Googe Hangout for distal co-working

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/overview#146]
The possibility of remote co-working either through fixed "office hours" or an informal open-a-google-hangout-when-we-can practice was raised in [the June 1 Community Call](https://hackmd.io/JwEwTAHGBm3AtAQxBa8AsBjdJ7AEYAMi8hAbIYQMyY1hlnBA?view). 

Let's use this issue to discuss the idea and maybe identify a good process (can the slackbot help us? Should we just drop a hangout link in #dev when we're available?).

**Comment by patcon** [comment]
Two options, **depending if we want to easily record** when something important is being discussed.

1. if we **don't** care about recording:** create a gcal event for distant future, add a hangout to that event, and use that link forever. (this is a well-known tactic.) Perhaps make a short link. people always jump into that for office hours / coworking: https://productforums.google.com/forum/#!topic/hangouts/CWlBcLCOafc
2. if we **do want** option to record: might be an option with [YouTube Live Event dashboard](https://www.youtube.com/my_live_events), possibly also pre-scheduled way in advance

**Comment by patcon** [comment]
If we just want a video call perma-link without recording, ie (1), then I created an event with link:

https://hangouts.google.com/hangouts/_/w4745br4lzdr7mndmkayjuakyme

bitly-ized: http://bit.ly/edgi-archivers-hangout

![screenshot of calendar event](https://i.imgur.com/HY8VMen.png)

**Comment by dcwalk** [comment]
Hey @titaniumbones is this still something we're thinking of doing? My sense is likely not in the near future. If so I'm wondering if we can close the issue for now?

**Comment by dcwalk** [comment]
I'm going to close this as no one responded to my comment above! Maybe the new PM can strategize around how to best facilitate this :)
