### ISSUE TITLE
Trello-based onboarding demo for archiving project dev

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/overview#152]
Reticketed from #143

**Comment by dcwalk** [comment]
Is this issue (and the other demo one #153) pertaining to _just_ demoing the web monitoring onboarding workflow? 

Maybe we can schedule these for next weeks meetings if you feel like that timing works?

**Comment by dcwalk** [comment]
Add as a step to #143 demoing to us!

**Comment by dcwalk** [comment]
Based on the [September 11 Archiving call](https://hackmd.io/GwFgJgRgrGCMCGBaAxgU1WRIDMFP1gA4B2FeCEAgTm3mAAZgg===?view), I'm marking this as wontdo for now, and we can refile an issue around demoing onboarding as it moves forward.
