### ISSUE TITLE
Review GitHub repos and clean up

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/overview#155]
Just looking through stuff we have a few repos we should probably mark as archived, improvements to documentation, adding readmes and contributing docs, and renaming for clarity.

e.g.: #98 and https://github.com/edgi-govdata-archiving/analysis 
> ... I'm pretty sure this was addressed in https://github.com/edgi-govdata-archiving/analysis... which I think we need to rename and probably regig a bit.

TODOs to mark this round as done:
- [x] review all repos descriptions
- [x] add tags
- [x] review pinned repos
- [x] add description to those repos missing one
- [x] "ARCHIVE--" repos no longer under active development
- [x] update overview README

**Comment by dcwalk** [comment]
First pass review uncovered the following repos to further address:
- [x] **Website Monitoring**
    - [x] https://github.com/edgi-govdata-archiving/web-monitoring-differ (description?)
    - [x] https://github.com/edgi-govdata-archiving/go-calc-diff (rename? description?)
- [x] **Website**
    - [x] https://github.com/edgi-govdata-archiving/edgi-website (readme? contrib? description? rename?)
- [x] **EDGI-wide**
    - [x] https://github.com/edgi-govdata-archiving/analysis (description? readme?)
    - [x] https://github.com/edgi-govdata-archiving/fiscal (description? readme?)
- [x] **Archiving** 
    - [x] https://github.com/edgi-govdata-archiving/dataset-registries (archive? description?)
    - [x] https://github.com/edgi-govdata-archiving/archivers.space (description? readme?)
    - [x] https://github.com/edgi-govdata-archiving/zip-starter (rename? archive?)
    - [x] https://github.com/edgi-govdata-archiving/s3-upload-server (edit: ADD LICENSE)
    - [x] https://github.com/edgi-govdata-archiving/harvesting-tools (rename? archive?)

**Comment by dcwalk** [comment]
Hey @b5 --

Just going through and trying to clean up our no longer used repos, close out issues, update descriptions, etc...

For the Archivers space stuff, would it be alright if I:
1. prepend `archivers-` [`zip-starter`](https://github.com/edgi-govdata-archiving/zip-starter), [`s3-upload-server`](https://github.com/edgi-govdata-archiving/s3-upload-server), and [`harvesting-tools`](https://github.com/edgi-govdata-archiving/harvesting-tools)
2. add "ARCHIVED--" to the descriptions of all of those archivers tools
3. update the [archivers.space](https://github.com/edgi-govdata-archiving/archivers.space) repo readme to indicate this is no longer maintained...? (I'll ping you for review)
4. delete or transfer the repo/issue from the [`dataset-registries`](https://github.com/edgi-govdata-archiving/dataset-registries) to a helpful one in datatogether? (coverage?)

**Comment by b5** [comment]
I think all of the above sounds like a great idea! Of all of them, the `s3-upload-server` has the best chance of being useful in outside contexts IMHO.

But yes, you have my fullest support in doing all 4, let me know if you need a hand!

**Comment by dcwalk** [comment]
Okay! I'll do 1-3. 

Do you have a sense of a place for that `dataset-registries` convo? It was interesting! But maybe at this point mostly historical?

**Comment by dcwalk** [comment]
I transferred `dataset-registries` to Data Together org: https://github.com/datatogether/dataset-registries
