### ISSUE TITLE
Onboarding feedback

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/overview#156]
@linamnt gave the following feedback on [our webmon onboarding](https://trello.com/b/FCGGEaQq/edgi-web-monitoring-project-onboarding) in a Slack message. Thanks Lina!

> Hi Pat, here is the rundown of my onboarding process so far, I'm currently at the "Review Developer Oboarding Video" step, just need to sit down and watch it!
>   - [x] copying trello board was harder than expected, but I didn't really follow all the instructions! (See #158 -- @patcon)
>   - [ ] wasn't sure if I needed to make an account when watching UI demo or the next step when exploring the app, i.e. I though my job was to use that app, perhaps some context about the "analysts"/grad students before the video?
 >  - [ ] very minor: some points don't have to-do-lists which is somehow disappointing for someone who likes checklists as much as I do

**Comment by patcon** [comment]
Just noting that the first point here is being tracked in #158, so going to check that off

And added checklists for all the active cards (some work-in-progress cards don't have them). This is my new favourite card :) https://trello.com/c/ZoaSMbpy/8-explore-the-live-app

**Comment by dcwalk** [comment]
Hey @patcon can we reformulate this issue (title) so it can be resolved? Not sure what the next steps here are, if any.

**Comment by patcon** [comment]
Updated [UI demo card](https://trello.com/c/2zugEagn/9-review-analyst-training-video) to address lina's second comment.

Previous version:
> Analysts work hard! Empathizing with their job is helpful :)
>
> This will help you understand the legacy spreadsheet-based process that we're trying to improve on with the new UI.

Current version:
> Analysts are the ones who will use the software you'll be building. They work hard!
>
> Before building the software, it's important to build empathy for the folks whose process we're working to improve :)
>
> Watching this video will help you understand the legacy spreadsheet-based process that we're trying to improve on with the new system.

Related: https://github.com/edgi-govdata-archiving/overview/issues/171 (re: manually documenting trello changes.)
