### ISSUE TITLE
Upload archiving/tech meeting video to youtube

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/overview#157]
From EDGI Zoom account
https://zoom.us/recording/detail?meeting_id=c6CG2NOLQuWd150l2%2B7UtA%3D%3D

As per @dcwalk request, crop beginning and end.

(I'm on mobile and can't upload big video right now)

**Comment by dcwalk** [comment]
This was done: https://www.youtube.com/playlist?list=PLtsP3g9LafVsmicfDxSGxB9imUgZODCGg
Cut off the last 30 and first ~5mins (also-- we had an odd artifact of someone elses recording at the beginning 👻 _spooky_

**Comment by patcon** [comment]
I know! I saw that! Weird. If @zoomvideo actually had any _people_ listed on their github, i would @mention them so they could investigate, but alas... :)
