### ISSUE TITLE
Connect Slack(s) to CodeForAll network

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/overview#159]
Not sure if this makes sense for us, but putting it out there.

Could do Archivers and/or EDGI. It can just be a single room (ie. not connecting to the main `#general` channel or anything.

Connection link:
https://slackline.io/shared_channels/qQKCwG9gViYVxYuhoU3ZhQ

**Comment by dcwalk** [comment]
Hmmm, I think EDGI wouldn't be a fit...? I could see it working with Archivers (and actually maybe seeing if ProgCode does something similar?)

**Comment by dcwalk** [comment]
I'm going to go ahead and close this as won't do, as there didn't wind up being continued discussion. Let me know if you think this should remain open however!
