### ISSUE TITLE
Add EDGI credit card to Heroku

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/overview#160]
I am very uncomfortable with my Heroku account being used for hosting apps that may be important to EDGI. Frankly, my credit card situation is unstable, and so being tied to my account is an accident waiting to happen.

Specifically:
- the halpy chatbot
- the video call landing page
- soon, the slack bridge

The apps above are all free right now, but if Heroku ever can't pull a payment for **any of my personal paid app**, it puts all app (free or paid) into maintenance mode.

Does EDGI have a credit card? How can I move this forward?

**Comment by titaniumbones** [comment]
Although there have been some issues with this in the recent past (!), I
think we could probably put this on my credit card. tagging
@murphyofglad since it belongs to both of us!

**Comment by dcwalk** [comment]
I could also probably if needed. 

I'd love to do a prelim consolidation of heroku stuff too this week if possible! I think I have one and we have the EDGI acct. Would be good to set up the team properly :)

**Comment by patcon** [comment]
Seems that teams are kinda limited:
https://devcenter.heroku.com/articles/heroku-teams#pricing-and-limits

- free for 5 people
- $10/month for up to 25 people
- can't have free apps in team (ie. $7/month, but this seems odd, so worth confirming by testing)

So given the above, I suggest:
1. We attach one credit card to both the team, and to enviroDGI@gmail.com account
2. We test teams to confirm those "cons"
3. If true, we just give ownership of all our apps to that account, and make everyone else collaborators (unlimited number of collabs on free apps).

**Comment by dcwalk** [comment]
@patcon can we connect on this? Seems important :)

**Comment by dcwalk** [comment]
My card is on this now, we'll regroup in September and see if it could/should be adjusted. Closing!
