### ISSUE TITLE
Experiment with in-slack decision-making protocol

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/overview#165]
Thought maybe we could try something for in-slack decision-making. This is my proposal, which is open to suggestions, and is certainly expected to change after we try it:

1. I'll make a post asking a clear question.
1. I'll use `@channel`.
1. I'll link to any larger context. (GitHub, etc.)
1. I'll be clear about the decision timeframe. (ie. point after which action will be permitted if supported.)
1. I'll add the "#decision" hashtag at the end.
1. I'll add a reaction emoji :spiral_notepad: for "labelling" it as a decision.
1. I'll seed it with some other emoji, for encouraging specific responses:
    1. :+1: Agree
    1. :neutral_face: Neutral.
    1. :-1: Disagree.
    1. :question: Have questions.
    1. :thinking: Thinking about it.
    1. :clock2: Plan to get to this later.
1. People can add other emoji reactions, if those provided don't suit them.
1. Message should request that related msgs be "threaded".

Benefits:
1. easy to search/find in slack (via hashtag or emoji reaction)
2. visual and easy to skim (avoids extraneous words when possible)
3. simple to automate with hubot if we feel like it (eg. anything with `#decision` is tagged with emoji, and an "explainer" doc is dropped as a threaded reply, blah blah)
4. leverages features of Slack tool that already exist
5. "extensible" and adaptable via emoji reactions
6. requires zero programming to start with

Any thoughts on this as an minimum viable idea? (Hoping to use it for setting up slack bridges.)

**Comment by patcon** [comment]
In particular, curious whether anyone has thoughts on emoji: are there better alternative emoji? Could the "legend" use better terms? Should there be less or more?

(Keep in mind: Slack's differ slightly, but we can also upload our own.)

**Comment by patcon** [comment]
cc: @titaniumbones (i thought we had an related issue... but can't find anything!)

**Comment by dcwalk** [comment]
It appears that we settled on a biweekly coordination call for Archiving and Web Monitoring has weekly meetings. I'm marking this as `wontdo` for now but I'm also leaving this open while the Archiving WG transitions as maybe we want to revisit :))
