### ISSUE TITLE
Configure and document IRC bridge for Archivers Slack

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/overview#166]
Reticketed from https://github.com/edgi-govdata-archiving/web-monitoring/issues/36#issuecomment-305651869.

@neiljp asked:
> I'm generally not on Slack; is there an IRC mirror somewhere?

There was also [Slack convo](https://archivers.slack.com/archives/C3XS9LPJN/p1496362907790262) back at the start of June.

## To Do

- [x] configure Slack IRC gateway (h/t @b5?)
- [x] document and link from relevant places

cc: @titaniumbones @neiljp @Mr0grog

**Comment by patcon** [comment]
I think @b5 enabled the gateway earlier, so available here to every Slack member:
https://archivers.slack.com/account/gateways

**Comment by patcon** [comment]
Since webmon onboarding is somewhat authoritative, added details to card here:
https://trello.com/c/WeZ7FLNa/3-join-archivers-slack-chat

It should go elsewhere in high-level static docs though before this is done.

**Comment by patcon** [comment]
@neiljp curious where you personally think the info in that trello card would best fit, so that it was on your critical path when you came on.

Also, we're all ears if you have any other tips on how to improve the details on that Trello card :)

**Comment by dcwalk** [comment]
@patcon -- can you also add details to the README in this overview repo? As the trello onboarding is project-based ATM there are still people who are new who don't visit trello.

**Comment by dcwalk** [comment]
Just looking at the checklist @patcon -- what other "relevant places" should we be documenting IRC gateway in for now?

**Comment by dcwalk** [comment]
ping @patcon this seems like a small-sized issue and I'd love to close it out, but not sure where else you want to document?

**Comment by dcwalk** [comment]
We discovered this is done! I'm closing 🎉
