### ISSUE TITLE
Create ical proxy to filter out non-public events

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/overview#168]
Would be rad if we could maintain as few calendars as possible, but still share some events in there more freely.

If we created a filter proxy app, we could give it the private ical url, and get a filtered calendar.

This app could do one of two approaches:
1. it could **skip** any events with a tag like `#private` in the description
2. it could **only include** events with a tag like `#public` in the description.

Approach (2) is probably more aligned with EDGI values, as it would be a forgiving default. eg. and EDGI member naively creating a new event wouldn't run the risk of publicizing it and having undesired drop-ins.

We could fairly easily create this app, and hardcode it for our calendar, so that sharing a filtered ical feed would be as simple as https://edgi-public-calendar.herokuapp.com/edgi-public-calendar.ical

**Comment by patcon** [comment]
fwiw this is already a thing, but written in .NET, and not quite what we need, and probably not worth patching.
Source: https://github.com/taurit/CalendarProxy
Hosted: https://todoistcalendar.azurewebsites.net/

Tested the service, and it worked for skipping events with keywords, ie. approach (1), but would need a new feature for approach (2) to work. Also, critically, **this app would reveal the original private ical url**, which defeats the purpose of filtering.

**Comment by dcwalk** [comment]
@patcon -- we have a public EDGI calendar: https://envirodatagov.org/events/ (airtable backend) and I know @lourdesvera was excited about using a wordpress event manager as well at some point in the future, that airtable events link exports fairly easily for that... we did some prelim testing in April. 

Is there someway that we could just publish to that instead of a new service?
Airtable has an API

**Comment by patcon** [comment]
Ah, I totally forgot about that! Thanks! :)

The calendar I'm wishing we had is one that everyone liberally adds to... I'm not sure airtable feels like that place:

Here's a couple facts informing/weighing on my feelings here:

:mag: EDGI already uses Airtable.
:mag: EDGI already uses Google Calendar.
:mag: Airtable has unlimited users so long as we're in free tier.
:mag: Airtable [pricing](http://airtable.com/pricing) super-restricts user access after 1,200-row free tier (which I just checked, and we're over?)
:mag: Airtable has a nicer api than gcal
:mag: A chatbot command provides very limited access.
:mag: a chatbot command is difficult to make full-featured.
:mag: Everyone has free access to full gcal interface.
:mag: Many people (most?) already have Google accounts that they use regularly.

I'm open to whatever the folks working together on the calendar prefer, but I have more positive vibes about gcal over airtable as a participatory tool.

**Comment by patcon** [comment]
:mag: Airtable seems to put effort into modern visual look.

**Comment by patcon** [comment]
Sorry, tl;dr -- calendars feel important to a community, and so I have lots of personal feels on where they could live and how we all interact with them :) would love to chat more fully in a less niche space as this! :heart:

**Comment by dcwalk** [comment]
Hey! This happened by other means :))))

The website now reflects the EDGI events: https://envirodatagov.org/events/
