### ISSUE TITLE
Implement hackfoldr backup

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/overview#173]
Would be nice to ensure we have backups of hackfoldrs that we might be using for project work. Hackfoldr keeps a revision history via ethercalc, but would be nice to keep it in git to make it more transparent.

g0v should have something we can steal, as they definitely had this concern as well.

Related: #149

**Comment by dcwalk** [comment]
We've officially retired the hackfoldr after many conversations on slack, closing as `wontdo`
