### ISSUE TITLE
Add patcon SSH key to Compute Canada

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/overview#183]
yeow! ssh key: https://github.com/patcon.keys

This is the minimal that I would need to move my Jenkins instance from my personal DigitalOcean account into an EDGI-controlled environment.

This is related to https://github.com/edgi-govdata-archiving/overview/issues/149

**Comment by dcwalk** [comment]
After our chat yesterday @patcon I think it is safe to close this! Let me know tho if you'd like it re-opened and to get you on compute canada stuff :)
