### ISSUE TITLE
Add patcon account to Compute Canada

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/overview#184]
Bonus points above #183

As a contractor, patcon now has a UTORid card: connol31

Caveat: might only be valid until September 1st. Assuming they're on the ball with removing access (which they may not be), then perhaps it's not worth the trouble of setting this up.

**Comment by dcwalk** [comment]
I looked into this and I can't add you to any accounts. 

You have to complete the steps to get you added, not sure if your are eligible:
1. https://ccdb.computecanada.ca/ "Register"
2. apply to be added to a project (Michelle is the only one who can PI)
3. if request is approved, apply for access to East Grid: https://east.cloud.computecanada.ca/
4. have that acct linked with the project ID

This will be only valid till Sept 1, and I think they set the expiry pretty tight (I just had to re-auth as I didn't log in to these admin panes yet this RAC cycle)

From what I recall it took me more than 2 weeks to get up and running. I think that #183 is a more realistic option. Closing this for now, but re-ticket getting yourself added if you pursue?

**Comment by patcon** [comment]
Yeesh. How did I miss this?

Currently awaiting information for registration from @murphyofglad via Slack: https://archivers.slack.com/archives/C5E8PS7U2/p1504578201000100
