### ISSUE TITLE
Pin disclaimer to message in each bridged channel

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/overview#187]
Related: https://github.com/edgi-govdata-archiving/overview/issues/154

Slack context: https://edgi.slack.com/archives/C4H23J40J/p1502400481729122?thread_ts=1502381075.026913&cid=C4H23J40J

For ease of updating, I have to text in one place in a hackmd notepad: https://hackmd.io/s/BJWOLQBrZ

# To Do

- [x] Add disclaimer link in pinned post to all channels
- [x] Create ticket upstream to track this new deficiency of bridge (shared posts not going through)

**Comment by dcwalk** [comment]
In addition to Pinning @patcon, can we edit the purpose & topic? I find that I almost never see the Pinned messages until much later when joining a channel, some prompt in the description would help

**Comment by dcwalk** [comment]
I think this might be a good thing to verify at least on the EDGI end, also quick. Thoughts @lightandluck?

**Comment by lightandluck** [comment]
I've added new pinned messages to each bridged channel and edited the topics of the channels with more information on bridging: https://hackmd.io/3fZbzWBfRZGpbpD_V-1GhQ?view

Also opened a related issue: #234
