### ISSUE TITLE
Archive pertinent datasets for Doris Duke

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/overview#194]
Spinning out of #119 it looks like we don't have a place where we are tracking out progress/intention to complete archiving datasets as part of our work around the Doris Duke grant. 

There are previous [in-Slack](https://edgi.slack.com/archives/C32V5KUBA/p1497535812665513?thread_ts=1497085512.418775&cid=C32V5KUBA) conversations around this.

**Comment by dcwalk** [comment]
@b5 can you give an update on this?

**Comment by b5** [comment]
Update time! 

After examining the list, I think for the of a number of these urls we should focus on building collections. A trivial example uses this url from the listed EPA sheet: https://www.epa.gov/endangered-species/biological-evaluation-chapters-chlorpyrifos-esa-assessment
which, after archiving & adding as a collection, will look like this: https://archivers.co/collections/6cfbb25c-3ff1-4565-8c4e-897ccebd1280

the upside of these collections is we can continually refine their archival quality after they've been initially created. I'm focusing on a bunch of cleanup to make these collections work, but in the meantime, we do have to actually _create_ the list of urls for each collection.

I've written up a quick tool to help with the collection creation process: http://github.com/datatogether/extract_href, which includes instructions for installation use. But the process should be: 
1. Take a url from the list. (@dcwalk should we use archivers.space to check it's status?) 
2. check to see if page contains links to data stored as HTML, if so `extract_href` will work.
3. use `extract_href` to build a list of urls, write it to a file with the `-o [filename.txt]`
4. check the urls it produces, removing irrelevant urls that don't point to data
5. post a gist of that file (and link it back in the spreadsheet? in archivers.space?)

@dcwalk & co, it would be amazing if we could rally up some folks to check through our list of deliverables. We can then use these files to generate the collections for archiving.

I'm working on a small set of of bug fixes to make the actual collection creation process work smoothly, hoping to ship that in the next day. It works today, it's just painful and full of gotchas that we can round out, I'll post an update here once they're up.

Not every url will work for this (some will need custom crawling), we'll use the custom crawling work out of Boston for those urls. Speaking of custom crawls & team Boston, @jeffreyliu I'm hoping we can walk through this `extract_href` sometime toward the end of this week. While writing the `extract_href` tool I realized two things:
1. This should really all be rewritten in python & built into the custom crawling toolkit
2. This codebase is a perfect introduction to the go programming language.

So, on either Thursday or Friday I'd love to do an open session that walks through everything that codebase does so we can talk about converting it to python, but also serve as an introduction to go for anyone who's interested. cc @patcon just to know that I'm angling to plan a community-oriented conversation 😄.

**Comment by dcwalk** [comment]
During our [September 11 Archiving call](https://hackmd.io/GwFgJgRgrGCMCGBaAxgU1WRIDMFP1gA4B2FeCEAgTm3mAAZgg===?view), this was indicated as an ongoing and important priority. Moving to the [Fall Work Cycle](https://github.com/edgi-govdata-archiving/overview/milestone/2) milestone

**Comment by jeffreyliu** [comment]
I'm free Thursday before/after community call and yes, this does sound like
it'd be a good fit for the archivertools package and also would be cool to
learn go from this. I'll create an issue in that repo for the porting work.

**Comment by dcwalk** [comment]
Okay, so this happened, closing!
