### ISSUE TITLE
Wind down issue queues without disappearing prior issues

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/overview#198]
Related to https://github.com/datatogether/archivertools/issues/5#issuecomment-320113956

> I'm not able to see the linked issue, it's giving me a 404. Is there text beyond the quote that I'm not seeing?

["Probot: Workflow" plugin](https://github.com/probot/workflow) could be enabled across the github org, and dropping a specific custom `.probot.js` file could:

1. Auto-respond saying that the repository has been deprecated.
2. Close the issue.
3. Lock it?

Alternatively, we could decide not to disable issue queues on existing repos.

**Comment by dcwalk** [comment]
@patcon -- I think that might have been a one off problem the day that github was choking on pretty much every request... the issue was merely closed: https://github.com/edgi-govdata-archiving/archivers-harvesting-tools/issues/8

**Comment by dcwalk** [comment]
I'm going to close this as handled, per my comment above. If you feel like it should be re-opened, or there is something I've missed, please let me know!
