### ISSUE TITLE
Rename `mozsprint` label to `Hacktoberfest`

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/overview#206]
Slack context: https://archivers.slack.com/archives/C3XS9LPJN/p1506974925000248

[Hacktoberfest](https://hacktoberfest.digitalocean.com/) could definitely do with more thought, but at the very least, we should rename our labels and catch some folks who are searching github anyhow.

## Action Items

- rename for the following repos
  - [x] web-monitoring-db
  - [x] web-monitoring
  - [x] web-monitoring-processing
  - [x] overview

h/t @Mr0grog for label rename suggestion :label:

**Comment by patcon** [comment]
Related: https://github.com/edgi-govdata-archiving/web-monitoring-db/issues/154

**Comment by Mr0grog** [comment]
🙌
