### ISSUE TITLE
Review Code of Conduct

### ISSUE THREAD

**Issue by weatherpattern** [edgi-govdata-archiving/overview#207]
A new contributor on another repo didn't see a code of conduct and suggested one based on this:
http://contributor-covenant.org/version/1/4/

@danielballan and I like it because it describes specific promoted and unacceptable behaviors. Also it add a point of contact.

I think some of this was also brought up in our working with partners best practices.

Thoughts?

**Comment by dcwalk** [comment]
Hey @weatherpattern, two things! 

1) Each repo should reference the CoC in the readme, I thought that was indicated in the [Project guidelines](https://github.com/edgi-govdata-archiving/overview/blob/master/guidelines/project_guidelines.md), but it appears not.

2) We are using the EDGI CoC that cuts across all events, spaces etc... so I think this conversation might have to happen at a different level? (e.g., kicked off at a Weekly Meeting, aligned with making the protocol for ECGI public, etc...!)

**Comment by weatherpattern** [comment]
Thanks @dcwalk 

1. So, in the short term, I can make sure the current CoC is referenced everywhere.

2. Yes,  not surprised that this is a larger conversation. Maybe our repos have a combination of the two, a general one like we have now, but then also a supplement with open source code specific guidelines.

**Comment by dcwalk** [comment]
+1 to adding the reference, maybe submitting a PR on the guidelines in this repo and thinking about connections to some of the issues that @patcon was thinking of last summer #170 #179 #186?

Also-- I think all the things you talked about RE: CoC the GitHub (and EDGI's) should have. So I think a near term goal would be improving the CoC (I'm thinking like proposal-driven model so show a draft of what you are thinking at a weekly call) then have some of that flow 'up' to the protocol?

**Comment by Frijol** [comment]
Re ensuring CoC visibility in every project, I've seen top-of-readme badges like this one [![Code of Conduct](https://img.shields.io/badge/%E2%9D%A4-code%20of%20conduct-blue.svg?style=flat)](https://github.com/edgi-govdata-archiving/overview/blob/master/CONDUCT.md) work well

**Comment by Frijol** [comment]
Heads up that I'm tracking application of the badge in [this spreadsheet](https://docs.google.com/spreadsheets/d/1IcPchZkOGjQnTUqRb9oH01Q9B7zZSAKtdU1F9mA51QA/edit#gid=0) which I made for the [Repo Audit issue](https://github.com/edgi-govdata-archiving/overview/issues/217)

**Comment by Frijol** [comment]
We did it! 🎆 🎊 💃
