### ISSUE TITLE
Review and update this repository to reflect current Archiving/Comm. Tech efforts

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/overview#208]
We've gone through a quieter period over the last ~6 months, but are at the start of a more sustained period of attention.

Would be good to update this repository to reflect that, drawing on existing EDGI documentation:
- Archiving Roadmap
- Archiving Process

(potential) TODOs to mark as complete
- [x] update readme to remove inactive projects
- [x] close stale issues 
- [x] provided updates on ongoing issues
- [ ] confirm/review tools for project tracking for Archiving milestones
- [ ] publish updated Archiving roadmap and processes

Related issues:
- #207 
- #193

**Comment by Frijol** [comment]
I think https://github.com/edgi-govdata-archiving/overview/pull/215 resolves the two unchecked boxes as much as makes sense for right now– ok to close?
