### ISSUE TITLE
Standard template for Contributing on other repos

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/overview#218]
~As part of fulfilling https://github.com/edgi-govdata-archiving/overview/issues/179 (make sure all active repos have contributing guidelines) I started looking at what repos do/don't have guidelines.~

~Lots of them don't (see the repo audit at https://github.com/edgi-govdata-archiving/overview/issues/217)! The ones that do have them don't match but express different useful ideas– let's make a template for what CONTRIBUTING.md should look like based on the strengths of the various boilerplates and put it in the template discussed in https://github.com/edgi-govdata-archiving/overview/issues/170~

~To complete, we should have a standard Contributing.md that refs back to the canonical one, then check that it's applied to each of:~

**Update:** standard can be found at https://github.com/edgi-govdata-archiving/overview/blob/master/repo_guidelines.md#minimal-contributing-guidelines– to resolve, simply apply the template to the below repos!

  * [x] [edgi-scripts](https://github.com/edgi-govdata-archiving/edgi-scripts)
  * [x] [edgi-hubot-halpy](https://github.com/edgi-govdata-archiving/edgi-hubot-halpy)
  * [x] [web-monitoring-processing](https://github.com/edgi-govdata-archiving/web-monitoring-processing)
  * [x] [eis-search](https://github.com/edgi-govdata-archiving/eis-search)
  * [x] [web-monitoring-versionista-scraper](https://github.com/edgi-govdata-archiving/web-monitoring-versionista-scraper)
  * [x] [web-monitoring-ops](https://github.com/edgi-govdata-archiving/web-monitoring-ops)
  * [x] [web-monitoring-db](https://github.com/edgi-govdata-archiving/web-monitoring-db)
  * [x] [web-monitoring](https://github.com/edgi-govdata-archiving/web-monitoring)
  * [x] [web-monitoring-ui](https://github.com/edgi-govdata-archiving/web-monitoring-ui)
  * [x] [matterbridge-heroku](https://github.com/edgi-govdata-archiving/matterbridge-heroku)
  * [x] [edgi-website](https://github.com/edgi-govdata-archiving/edgi-website)
  * [x] [archivers-greetingslack](https://github.com/edgi-govdata-archiving/archivers-greetingslack)
  * [x] [halpy-ng](https://github.com/edgi-govdata-archiving/halpy-ng)
  * [x] [100days](https://github.com/edgi-govdata-archiving/100days)
  * [x] [awesome-website-change-monitoring](https://github.com/edgi-govdata-archiving/awesome-website-change-monitoring)
  * [x] [edgi-acronym-expander-browser-ext](https://github.com/edgi-govdata-archiving/edgi-acronym-expander-browser-ext)
  * [x] [video-call-landing-page](https://github.com/edgi-govdata-archiving/video-call-landing-page)
  * [x] [eot-nomination-tool](https://github.com/edgi-govdata-archiving/eot-nomination-tool)

**Comment by Frijol** [comment]
Here's a proposed template based on ones we already have:

---

# Contributing Guidelines

We love improvements to our tools! EDGI has general [guidelines for contributing][edgi-contributing] and a [code of conduct][edgi-conduct] for all of our organizational repos.

## Here are some notes specific to this project:
Use this section for any contributing guidelines specific to the repo. For example:
* [Web monitoring's processing repo guidelines](https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/master/CONTRIBUTING.md) mentions which issues should be made on that repo versus on the main web monitoring repo
* In the [Web Monitoring umbrella repo's contribution guidelines](https://github.com/edgi-govdata-archiving/web-monitoring/blob/master/CONTRIBUTING.md), a style guide, testing best practices, and notes on how work is distributed (process) are laid out
* The guidelines on [the EDGI Scripts repo](https://github.com/edgi-govdata-archiving/edgi-scripts/blob/master/CONTRIBUTING.md), [video call landing page](https://github.com/edgi-govdata-archiving/video-call-landing-page/blob/master/CONTRIBUTING.md) and [100 Days](https://github.com/edgi-govdata-archiving/100days/blob/master/CONTRIBUTING.md) discuss important notes on how the continuous integration is configured
* [The website's contributing guidelines](https://github.com/edgi-govdata-archiving/edgi-website/blob/master/CONTRIBUTING.md) tell you where to find the appropriate Slack channel


   [edgi-conduct]: https://github.com/edgi-govdata-archiving/overview/blob/master/CONDUCT.md
   [edgi-contributing]: https://github.com/edgi-govdata-archiving/overview/blob/master/CONTRIBUTING.md

**Comment by Frijol** [comment]
Suggestions for inclusion in standard Readmes:

* Highlight "ready" label on issues (pending https://github.com/edgi-govdata-archiving/overview/issues/193) to mean "this is an issue that is ready to work on and needs an owner"
* Add badges to the top including [![first-timers-only](https://img.shields.io/badge/first--timers--only-friendly-blue.svg?style=flat-square)](https://www.firsttimersonly.com/) linking to "good first issue" label, [![Code of Conduct](https://img.shields.io/badge/%E2%9D%A4-code%20of%20conduct-blue.svg?style=flat)](https://github.com/edgi-govdata-archiving/overview/blob/master/CONDUCT.md)
* "[All contributors](https://github.com/kentcdodds/all-contributors#emoji-key)" listing
* "How to start contributing to this repo" section including developer setup (if relevant), Slack channel

**Comment by Mr0grog** [comment]
We should link (or include) the style guide for the code, if there is any.

**Comment by lightandluck** [comment]
This template looks great!

+1 adding style guide as example in template. See umbrella [web-monitoring](https://github.com/edgi-govdata-archiving/web-monitoring/blob/master/CONTRIBUTING.md) repo

**Comment by Frijol** [comment]
That makes sense. Style guide is considered to be per-repo rather than an EDGI standard?

**Comment by Mr0grog** [comment]
The web monitoring one applies to all `web-monitoring-*` repos, but wasn’t done in any way that was coordinated across other EDGI projects. It overlaps a lot with what `web-monitoring-ui` has (and that’s the only one that has explicit coding style guidelines, IIRC), so it’s all a little messy. I *think* I’d prefer there only be one for all the projects (and it needs to clarify which rules are language agnostic and which are for a particular language). So, uh, it’s messy.

My ideal would be potentially per-repo, but in most cases many repos would share (e.g. one guide for all web monitoring repos). I think we’d have a hard time agreeing on rules across all EDGI repos, but maybe I’m being pessimistic.

**Comment by Frijol** [comment]
~Currently blocked by https://github.com/edgi-govdata-archiving/overview/pull/220 – once template is accepted there, I can apply it to the repos~ *merged, can proceed now!*
