### ISSUE TITLE
Add CLA bot to all repos

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/overview#219]
We should probably talk about this at some point, My understanding is that it applies to us too, even though we're not a traditional company

https://github.com/ColinEberhardt/cla-bot

https://www.clahub.com/pages/why_cla

**Comment by Mr0grog** [comment]
This is a reasonable thing to talk about, but it affects everything in the edgi-govdata-archiving org. I’m not sure it’s really a Web Monitoring discussion.

**Comment by lightandluck** [comment]
Still sounds relevant and moved to `overview` repo

**Comment by Frijol** [comment]
Is this something we can get legal advice on? CLA's can be a major barrier to contribution ("you want me to sign some contract before you'll accept my PR?"). Is it possible that we could include this as a piece of our Contributing or License docs ("by contributing to this repo you agree...")?
