### ISSUE TITLE
Should we revisit Heretrix?

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/overview#22]
Per conversation at Jan 17 Civic Tech TO, question was whether we should revisit Heretrix and get an instance up and running for testing 
(http://www.crawler.archive.org/index.html)

**Comment by mhucka** [comment]
Is there more information somewhere about the pros and cons of Heretrix and people's past experiences with it? Or to put it another way, why *aren't* people using it currently?

**Comment by mhucka** [comment]
Related to this: have people tried [Brozzler](https://github.com/internetarchive/brozzler)? I see that it's not listed on the [page of harvesters](https://github.com/edgi-govdata-archiving/harvesting-tools) (but then neither is Heretrix, so maybe I'm not looking where such things might be listed).

**Comment by dcwalk** [comment]
I'm going to close this as won't do, as the scope of this question isn't a fit with the current way we are orchestrating projects. Would assume questions about crawlers to take place in the ambit of Data Together (https://github.com/datatogether/roadmap/issues), if someone thinks this should be revisited let me know!
