### ISSUE TITLE
More explicit merge guidelines in CONTRIBUTING?

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/overview#224]
I'd like to have more explicit metrics around when something is ready for merge. Currently, I worry both that (a) PR's aren't getting seen by the people who might want to review them before merge and (b) PR's just sit there even after an "approve" review or two because it's not clear who all should review them. It feels fairly no-win and concentrates the power of repo maintenance into people who already feel a lot of ownership over a given project.

In our [Contributing guidelines](https://github.com/edgi-govdata-archiving/overview/blob/master/CONTRIBUTING.md), we say:

> Allow others sufficient time for review and comments before merging. We make use of GitHub's review feature to comment in-line on PRs when possible. There may be some fixes or adjustments you'll have to make based on feedback.

But what is "sufficient time"? How long should we leave approved (or un-commented-on) reviews open?

**Comment by Mr0grog** [comment]
In Web Monitoring, sufficient time is generally 3 days, unless there’s some strong reason to do something different (a hotfix That needs to go in now, or a deeply drastic change that would break everyone’s development environment and needs more time to break or people to see/review). What qualifies for being special in that way is fuzzy, so there’s no hard rule—being given commit permissions is an explicitly a vote of trust that you’ll make reasonable decisions here.

w/r/t *who,* the rules we’ve been following are reasonably explicit (I think), though we may have only discussed them in meetings:
- If you have commit permissions, you are responsible for merging your own PR (unless there is some extenuating circumstance). You should avoid merging without any review unless a sufficient time (see above) has passed with no feedback.
- If you don’t have commit permission, the reviewer is responsible for merging.
- Anyone who can commit can review, but is expected to be reasonable about whether they *should,* e.g. probably ask someone else to review if you don’t know much about the part of the codebase being worked on.
- Commiters who can review should also make reasonable choices about whether others need to review in addition and request them through GitHub or poke them on Slack. If neither the first reviewer nor the PR author ask for more reviewers, it doesn’t need more reviewers.

Obviously a lot about the above probably doesn’t scale well, but I don’t know if that’s a problem worth worrying about until we actually have lots of active contributors. Also obviously we’ve done a crap job laying that out in discoverable, written form.

**Comment by Mr0grog** [comment]
Also, apologies if you’ve left PRs sitting in web monitoring repos waiting for someone to merge them, unaware that we were expecting *you* to.

**Comment by Mr0grog** [comment]
@Frijol is there anything actionable here? Should we adopt (and make explicit) the Web Monitoring rules I attempted to codify above?

**Comment by Mr0grog** [comment]
Also, having seen some surprising (to me at least) usages of the term “hotfix” lately, I think I’d want to clarify that, too, since I mentioned it above. e.g:

> A hotfix is a quick solution to an active and serious problem that is causing unrecoverable data loss, whole systems to be unavailable, etc. The patch may be the minimum intervention necessary to address the failure, but will likely not be ideal (since it needed to be designed and programmed quickly). It should be reviewed by someone else, but may be merged and deployed without review if nobody is available to review it within a short timeframe. It should almost always be reviewed again after deployment and, if necessary, a better long-term fix should be planned.

**Comment by Frijol** [comment]
Yes, I think it would be great to have all of the above implicit rules in Contributing.md as a fix! Thanks for codifying these, it makes it really clear what's expected
