### ISSUE TITLE
Repos that don't have licenses

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/overview#227]
When I was doing the [repo audit](https://docs.google.com/spreadsheets/d/1IcPchZkOGjQnTUqRb9oH01Q9B7zZSAKtdU1F9mA51QA/edit#gid=0) I noticed that some of the repos don't have licenses.

1. Can we blanket-apply the [standard license](https://github.com/edgi-govdata-archiving/overview/blob/master/repo_guidelines.md#about-the-license) from the template?
1. Do we want/need to put licenses on the forks?

### EDGI repos
* [ ] [edgi-hubot-halpy](https://github.com/edgi-govdata-archiving/edgi-hubot-halpy)
* [x] [eis-search](https://github.com/edgi-govdata-archiving/eis-search)
* [x] [web-monitoring-ops](https://github.com/edgi-govdata-archiving/web-monitoring-ops)
* [ ] [edgi-website](https://github.com/edgi-govdata-archiving/edgi-website) (is it relevant to have a license here?)
* [x] [edgi-acronym-expander-browser-ext](https://github.com/edgi-govdata-archiving/edgi-acronym-expander-browser-ext) ([5a3582c086b5f3fc3247fd269faba02f2255775a](https://github.com/edgi-govdata-archiving/edgi-acronym-expander-browser-ext/commit/5a3582c086b5f3fc3247fd269faba02f2255775a))
* [x] [video-call-landing-page](https://github.com/edgi-govdata-archiving/video-call-landing-page) ([c1066f5fb9e58c07d56ba8e52e74940cf3576df4](https://github.com/edgi-govdata-archiving/video-call-landing-page/commit/c1066f5fb9e58c07d56ba8e52e74940cf3576df4))

#### No License file but has a readme block
* [x] [100days](https://github.com/edgi-govdata-archiving/100days) ([eef60527f29679ef7bbf26d76d1532459d682953](https://github.com/edgi-govdata-archiving/100days/commit/eef60527f29679ef7bbf26d76d1532459d682953))
* [x] [awesome-website-change-monitoring](https://github.com/edgi-govdata-archiving/awesome-website-change-monitoring) ([4f39634405c24eccf5355def0eb015454825c724](https://github.com/edgi-govdata-archiving/awesome-website-change-monitoring/commit/4f39634405c24eccf5355def0eb015454825c724))

### Forks
* [ ] [youtube-upload(fork)](https://github.com/edgi-govdata-archiving/youtube-upload)

**Comment by Frijol** [comment]
I suspect we *can* blanket-apply the standard license.

**Comment by Mr0grog** [comment]
FYI, web-monitoring-ops has since added a license.

**Comment by Mr0grog** [comment]
So… is this still important? Someone (or I) can go ahead and add licenses to these. Is the repo list in the OP still accurate?

**Comment by Frijol** [comment]
@Mr0grog thanks! I think the list is accurate but haven't checked in over a year I think

**Comment by Mr0grog** [comment]
Hmmmm, [edgi-hubot-halpy](https://github.com/edgi-govdata-archiving/edgi-hubot-halpy) has been archived. Should we still add a license there? (That requires un-archiving it.)

**Comment by Mr0grog** [comment]
> [edgi-website](https://github.com/edgi-govdata-archiving/edgi-website) (is it relevant to have a license here?)

Ah, yeah, I hadn’t realized there’s not even really an significant documentation or code there — and even if there were, it probably wouldn’t make sense to license for reuse. I’ll skip this one, too.

**Comment by Mr0grog** [comment]
> Do we want/need to put licenses on the forks?

*Technically, yes,* but our choice of license may be (*is,* in this case) constrained by the licensing terms of the thing we forked. BUT! In this case, I think we have removed all uses of it (as of edgi-govdata-archiving/edgi-scripts#55), so it maybe better to just archive it and leave it be.

/cc @lightandluck any thoughts there?

**Comment by Mr0grog** [comment]
Looks like a license has since been added to [eis-search](https://github.com/edgi-govdata-archiving/eis-search/commit/c473572a5ca3f4c5b421d933f3e9e61d2ecb5bd8).

**Comment by Mr0grog** [comment]
OK, I updated all the repos except the three kinda fuzzy ones I commented about above.

**Comment by Frijol** [comment]
Cool, thanks! And yay, we get to close this issue finally!
