### ISSUE TITLE
Migrate key documentation and tools from DataRefugePhilly event

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/overview#23]
Based on conversation prior to the event, we hope to pull some of the key documentaiton and toolkit knowledge from [DataRefugePhilly](https://github.com/datarefugephilly/) back into this EDGI repo to aid future events

Currently some exists here:
- https://github.com/edgi-govdata-archiving/harvesting-toolkit

**Comment by titaniumbones** [comment]
also here: 
- https://github.com/datarefugephilly/bagit-how-to
- and here: https://github.com/datarefugephilly/workflow

It's taken me a while to realize that you guys had a 3-part workflow of which the harvesting part is just an intermediary step. I think we should communicate this to future organizers as effectively as possible.  It sounds like the pressure is off at least a little, though, b/c the LA event will be ONLY a seed-a-thon, with a limited tech presence.

**Comment by librlaurie** [comment]
We've been working on big improvements to the workflow docs over at https://github.com/datarefugephilly/workflow. I hope you'll take a look and add/correct/improve. Thanks!

**Comment by dcwalk** [comment]
Just following up on this -- I'm marking this as won't do for now based on the approach we've taken: moving harvesting toolkit material into datarefuge workflow docs.
