### ISSUE TITLE
Extend stalebot time

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/overview#235]
Checking in on the Stalebot implementation– does it feel too aggressive? Many issues are getting marked stale/closed.

It's a bit more churn than I can personally keep up with, curious to hear how others feel.

@lightandluck weighed in on Slack:
> I think extending the time from when Stalebot closes an issue from 1 week to 2 weeks would help.

**Comment by Frijol** [comment]
Moving this from discussion format to to-do format, here's how to close this issue:

* Find the .yml file (in each repo I think?) that controls stalebot
* Extend the time between marking "stale" and closing the issue from 7 days to 14 days

**Comment by Mr0grog** [comment]
So… where does this need to be done in order to close the issue? Can we add a checklist to the issue description?

For my part, I’m not really bothered by the timeframe when it comes to web monitoring. (I have missed acting on it fast enough a few times, but giving myself another week would not have fixed the issue — it was always just less important than an endless list of other pressing things in every case, which I feel like is sort of when we want stalebot to close things.) That said, I’m happy to up the timeframe on the web monitoring repos if others think it would be helpful.

**Comment by Frijol** [comment]
Yeah, this has felt very non-urgent to change but I have a slight preference for expending our timeline to respond.

This would need to be done, unfortunately, in every repo that has the stalebot.yml (we have some closed issues in this repo which we could steal checkboxes from). (Is there a way to have one canonical stalebot.yml that all the repos pull from?)

**Comment by Mr0grog** [comment]
I don’t think there’s a way to effectively redirect to a different configuration file in a different repo, but we could make a script that updates all repos. Not perfect, but useful in that we could extend it to other things, like issue labels, etc.

**Comment by Mr0grog** [comment]
(Could also have a CircleCI job or GitHub action that runs the update whenever changes are made here.)


I’d be happy to help start or work on this if you think it’s worthwhile. Is JS, Python, or something else best for you?

**Comment by Frijol** [comment]
Seems like a good idea, though hard to feel urgent about it. If you have the capacity, I think it makes sense/reduces our long-term tech debt!

Personally I'm more comfortable in JS but have been doing more Python lately so either is fine for me! (Or a shell script?)

**Comment by Mr0grog** [comment]
Was thinking I would have some capacity for it this week, but alas, no. I’m still behind on figuring out what’s wrong with the Zoom → YouTube upload script. :(

**Comment by patcon** [comment]
Boop 👃👈 

https://github.com/probot/stale/issues/220#issuecomment-538467079

(Yep, that's right -- I booped you all on the nose and left a link for org-wide config 🙂 )

**Comment by lightandluck** [comment]
Thanks, @patcon for the link!

I think we should do this once we've moved repos to `main` #243.

**Comment by Frijol** [comment]
oh yayy fewer per-repo things to do

**Comment by Mr0grog** [comment]
This is great! We still have to delete the existing stalebot config from every repo, though. :P

**Comment by Mr0grog** [comment]
I don’t think there’s any major reason this can’t be happening at the same time as #243, though.

**Comment by lightandluck** [comment]
Yea, was just thinking it'd be more convenient to be able to do it all in one swoop without worrying about which was the default branch, but we're doing that bit by bit anyway, so this is just another addition to the list of transition tasks.

Rob, did you still want to find a way to automate this? Haven't worked enough with the different options suggested to recommend a choice among them.

**Comment by Mr0grog** [comment]
> did you still want to find a way to automate this?

Since this is a one-off operation (we’re just deleting `.github/stale.yml` from every repo), it’s probably not worth writing something re-usable for. But you could make a file that lists each repo, one per line, and run this in bash:

```sh
REPOS=`cat repo_list.txt`
for REPO in $REPOS; do
  echo "Fixing ${REPO}"
  git clone "${REPO}" workarea
  cd workarea
  git rm .github/stale.yml
  git commit -m 'Remove repo-specific stalebot configuration (we now have a global one)'
  git push
  cd ..
  rm -rf workarea
done
```

**Comment by Mr0grog** [comment]
But do we want to remove it from just one repo first and make sure the global one takes correctly?

**Comment by Mr0grog** [comment]
Ahhhh, I didn’t read the original well enough. We have to keep the stalebot config in each repo, but its only contents should be `_extends: .github`. So we’d alter the above bash accordingly.

Instead of:

```sh
  git rm .github/stale.yml
```

Do:

```sh
  echo '_extends: .github' > .github/stale.yml
  git add .github/stale.yml
```

**Comment by Frijol** [comment]
oh hm good catch. There are also other globals that might be worth checking out while we're at it e.g. I think we have global Contributing

**Comment by Mr0grog** [comment]
In any case, I made a PR to add the global config file in edgi-govdata-archiving/.github#4. We’ll still need to update everything else to reference it, but getting the file there so it can be referenced seemed like a no-brainer at this point. (It also updates the timeframe from 7 to 14 days.)

**Comment by lightandluck** [comment]
Adding checklist to keep track of progress:
- [x] https://github.com/edgi-govdata-archiving/overview 
- [x] https://github.com/edgi-govdata-archiving/eis-search
- [x] https://github.com/edgi-govdata-archiving/edgi-website
- [x] https://github.com/edgi-govdata-archiving/eot-nomination-tool
- [x] https://github.com/edgi-govdata-archiving/Template
- [x] https://github.com/edgi-govdata-archiving/edgi-scripts 
- [x] https://github.com/edgi-govdata-archiving/video-call-landing-page 
- [x] https://github.com/edgi-govdata-archiving/.github
- [x] https://github.com/edgi-govdata-archiving/100days 
- [x] https://github.com/edgi-govdata-archiving/matterbridge-heroku 

Web-Monitoring repos:
- [x] https://github.com/edgi-govdata-archiving/web-monitoring
- [x] https://github.com/edgi-govdata-archiving/web-monitoring-ui
- [x] https://github.com/edgi-govdata-archiving/web-monitoring-ops
- [x] https://github.com/edgi-govdata-archiving/web_monitoring_research
- [x] https://github.com/edgi-govdata-archiving/web-monitoring-processing
- [x] https://github.com/edgi-govdata-archiving/web-monitoring-db
- [x] https://github.com/edgi-govdata-archiving/web-monitoring-versionista-scraper
- [x] https://github.com/edgi-govdata-archiving/awesome-website-change-monitoring

EEW repos:

- [x] https://github.com/edgi-govdata-archiving/ECHO-COVID19
- [x] https://github.com/edgi-govdata-archiving/ECHO-Clean-Air-Act
- [x] https://github.com/edgi-govdata-archiving/ECHO-Clean-Water-Act
- [x] https://github.com/edgi-govdata-archiving/ECHO-Environmental-Crime
- [x] https://github.com/edgi-govdata-archiving/ECHO-Geo
- [x] https://github.com/edgi-govdata-archiving/ECHO-Hazardous-Waste
- [x] https://github.com/edgi-govdata-archiving/ECHO-Sunrise
- [x] https://github.com/edgi-govdata-archiving/ECHO-by-Zip-Code
- [x] https://github.com/edgi-govdata-archiving/EEW-Image-Assets
- [x] https://github.com/edgi-govdata-archiving/EEW-Website
- [x] https://github.com/edgi-govdata-archiving/EEW_Planning
- [x] https://github.com/edgi-govdata-archiving/Environmental-Enforcement-Watch

**Comment by lightandluck** [comment]
I'll be working on the misc EDGI repos right now!

**Comment by lightandluck** [comment]
Ran the script over all the EEW repos with a stalebot config file (not all of them did.) Thanks for the script, Rob!

Everything should be done!
