### ISSUE TITLE
Moving from `master` to `main` for unarchived EDGI projects

### ISSUE THREAD

**Issue by lightandluck** [edgi-govdata-archiving/overview#243]
This is a tracking issue for the [decision to move from master -> main](https://github.com/edgi-govdata-archiving/overview/issues/241) for existing repos.

This outlines the steps agreed with some great pointers from @jywarren and [how they did things for Public Lab repos](https://github.com/publiclab/plots2/issues/8077) and these [additional pointers](https://twitter.com/jywarren/status/1279856631271100416). (h/t @ericnost - Thanks, Eric!)

1. Create a new `main` branch from `master`.
2. Fix links where we can. Also be aware of any CI or hooks.
3. Create a final commit in `master` with a message in the README explaining the switch over. Should include these instructions on how local clones can make the switch as well. 

> If someone has a local clone, then can update their locals like this:
> 
> $ git checkout master
> $ git branch -m master main
> $ git fetch
> $ git branch --unset-upstream
> $ git branch -u origin/main
> $ git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main
> 
> The above steps accomplish:
> 
>     Go to the master branch
>     Rename master to main locally
>     Get the latest commits from the server
>     Remove the link to origin/master
>     Add a link to origin/main
>     Update the default branch to be origin/main

4. Make the `main` branch the default branch in the settings.
5. Re-point any open pull requests to `main`.
6. Require 1 PR approvals (restriction applies to administrators, too) on `master` branch as a reminder not to work on it going forward

Checklist of repos that are not archived:
- [x] https://github.com/edgi-govdata-archiving/overview 
- [x] https://github.com/edgi-govdata-archiving/eis-search
- [x] https://github.com/edgi-govdata-archiving/edgi-website
- [x] https://github.com/edgi-govdata-archiving/eot-nomination-tool
- [x] https://github.com/edgi-govdata-archiving/command (archived - we don't use this)
- [x] https://github.com/edgi-govdata-archiving/Template

Needs further investigation:
- [x] https://github.com/edgi-govdata-archiving/edgi-scripts (issue with switching to main)
- [x] https://github.com/edgi-govdata-archiving/video-call-landing-page (integrates with Heroku)
- [x] https://github.com/edgi-govdata-archiving/.github
- [x] https://github.com/edgi-govdata-archiving/100days (has a CI build step)
- [x] https://github.com/edgi-govdata-archiving/matterbridge-heroku (has integration with heroku)

Web-Monitoring repos:
- [x] https://github.com/edgi-govdata-archiving/web-monitoring-changed-terms-analysis
- [x] https://github.com/edgi-govdata-archiving/web-monitoring
- [x] https://github.com/edgi-govdata-archiving/web-monitoring-ui
- [x] https://github.com/edgi-govdata-archiving/web-monitoring-ops
- [x] https://github.com/edgi-govdata-archiving/web_monitoring_research
- [x] https://github.com/edgi-govdata-archiving/web-monitoring-processing
- [x] https://github.com/edgi-govdata-archiving/web-monitoring-db
- [x] https://github.com/edgi-govdata-archiving/web-monitoring-versionista-scraper
- [x] https://github.com/edgi-govdata-archiving/web-monitoring-task-sheets
- [x] https://github.com/edgi-govdata-archiving/wayback
- [x] https://github.com/edgi-govdata-archiving/awesome-website-change-monitoring

EEW repos:
- [x] https://github.com/edgi-govdata-archiving/CD-report
- [x] https://github.com/edgi-govdata-archiving/ECHO-COVID19
- [x] https://github.com/edgi-govdata-archiving/ECHO-Clean-Air-Act
- [x] https://github.com/edgi-govdata-archiving/ECHO-Clean-Water-Act
- [x] https://github.com/edgi-govdata-archiving/ECHO-Cross-Program
- [x] https://github.com/edgi-govdata-archiving/ECHO-DB-Views
- [x] https://github.com/edgi-govdata-archiving/ECHO-Environmental-Crime
- [x] https://github.com/edgi-govdata-archiving/ECHO-Geo
- [x] https://github.com/edgi-govdata-archiving/ECHO-Hazardous-Waste
- [x] https://github.com/edgi-govdata-archiving/ECHO-Sunrise
- [x] https://github.com/edgi-govdata-archiving/ECHO-Watershed
- [x] https://github.com/edgi-govdata-archiving/ECHO-by-Zip-Code
- [x] https://github.com/edgi-govdata-archiving/ECHOEPA-to-SQL
- [x] https://github.com/edgi-govdata-archiving/ECHO_modules
- [x] https://github.com/edgi-govdata-archiving/EEW-Image-Assets
- [x] https://github.com/edgi-govdata-archiving/EEW-Website
- [x] https://github.com/edgi-govdata-archiving/EEW_Planning
- [x] https://github.com/edgi-govdata-archiving/Environmental-Enforcement-Watch
- [x] https://github.com/edgi-govdata-archiving/echo-data
- [x] https://github.com/edgi-govdata-archiving/echo-ux-testing

**Comment by morrme** [comment]
First of all, thank you. ❤️  
Next, is this open to new contributors, or does it require someone who is a maintainer?

**Comment by ericnost** [comment]
@morrme thanks for asking! I think that in order to make the main branch the default branch in the repo's settings, you would need to have some sort of admin access, but can someone else confirm that?

**Comment by ericnost** [comment]
- [x] https://github.com/edgi-govdata-archiving/ECHO-COVID19

**Comment by jywarren** [comment]
@ericnost yes that's right. It's great to see you all getting this process going! Happy to offer input if it's helpful!

**Comment by Mr0grog** [comment]
> Require 6 PR approvals (restriction applies to administrators, too) on `master` branch

This seems a little excessive to me! Requiring an approval is good, but 6 just feels like it makes even useful changes too hard to bother.

The rest of this is super helpful, though. 🙏

**Comment by Mr0grog** [comment]
Updated:
- https://github.com/edgi-govdata-archiving/web-monitoring-changed-terms-analysis
- https://github.com/edgi-govdata-archiving/web-monitoring-task-sheets
- https://github.com/edgi-govdata-archiving/wayback

Will try to get to other Web Monitoring repos soon; now dealing with some Internet Archive problems. 😞 

EXCEPT https://github.com/edgi-govdata-archiving/web_monitoring_research, which I’ll leave to @ericnost.

**Comment by jywarren** [comment]
Awesome! Great to see this progressing! 🎉

**Comment by ericnost** [comment]
- [x] https://github.com/edgi-govdata-archiving/web_monitoring_research
cc @Mr0grog @lightandluck 

We are _probably_ going to archive
- https://github.com/edgi-govdata-archiving/ECHO-Clean-Air-Act
- https://github.com/edgi-govdata-archiving/ECHO-Clean-Water-Act
- https://github.com/edgi-govdata-archiving/ECHO-Hazardous-Waste
so they may not get moved over.

**Comment by lightandluck** [comment]
@Mr0grog Haha, true, it is excessive. Was thinking we didn't want folks push to `master` at all and couldn't find a setting like that. So wanted to set it to something that would set off alarm bells if someone tried and basically making it impossible.

But you're right, we might need to change something and don't think there's any PR approval requirements currently on any of the repos, so 1 should be enough. Edited it in the comment and changing in repos I had worked on.

**Comment by jywarren** [comment]
Oh this is really interesting methodologically - have you set the review requirement for the `master` branch only? It occurred to me that one could use a CODEOWNERS file in the `master` branch only to auto-trigger review requests to a specific team. https://github.blog/2017-07-06-introducing-code-owners/

Maybe it's solving a problem that doesn't exist, but i like the idea just as a neat trick that could make this process smoother for some communities. Anyways, just a thought!

**Comment by Mr0grog** [comment]
I’m not sure any EDGI projects currently have review requirements for the primary branch right now. As far as `CODEOWNERS`, I *personally* feel like it’s super useful for big projects where there really are different people or teams that own parts of the codebase, but kind of a weird hindrance from projects where that’s not the case — and most EDGI projects are not at all that big or complex, or at least they don’t have big teams with different ownership areas. Others might have a really different opinion, though!

What I wound up doing for the repos I updated was making sure only admins and maintainers can push to the `master` branch. That way review/feedback isn’t restricted or limited, but only certain people can actually hit the merge button.

**Comment by Mr0grog** [comment]
Updated:
- edgi-govdata-archiving/web-monitoring
- edgi-govdata-archiving/web-monitoring-ops
- edgi-govdata-archiving/web-monitoring-versionista-scraper
- edgi-govdata-archiving/web-monitoring-ui
- edgi-govdata-archiving/web-monitoring-processing
- edgi-govdata-archiving/web-monitoring-db

So all the Web Monitoring repos should be done.

**Comment by lightandluck** [comment]
Thanks, Rob! I've been hitting some roadblocks with the apps connected to Heroku, but making progress. More info in EDGI's private [Slack](https://edgi.slack.com/archives/C57QL8M1T/p1597255916008800).

**Comment by lightandluck** [comment]
@ericnost @Frijol @maalvikabhat 
Hey y'all, so we've done the switch for all unarchived EDGI repos and WM repos, besides the EEW repos. I have no idea what's in each and how they could be affected by this change. Can someone on the EEW team take a stab at it or write up what needs to happen if it's fairly consistent? Is this something that can happen near-term? I know there's a lot going on with Open Hours and such, so don't want to cause headaches while that's happening either.

**Comment by ericnost** [comment]
Hi @lightandluck, thank you so much for moving this along! I will see if Maalvika can work on this next week. In short, I don't think there should be any issues. We aren't sharing links to notebooks widely, and development is fairly minimal.

**Comment by ericnost** [comment]
- [x]  https://github.com/edgi-govdata-archiving/ECHO-Environmental-Crime
- [x]  https://github.com/edgi-govdata-archiving/ECHO-Sunrise
- [x] https://github.com/edgi-govdata-archiving/ECHO-Geo

Requires someone with permissions I don't have. I have created main branches in all or most, but I need someone else to approve and set up main as the default.
- [x]  https://github.com/edgi-govdata-archiving/EEW_Planning 
- [x]  https://github.com/edgi-govdata-archiving/ECHO-Clean-Air-Act 
- [x]  https://github.com/edgi-govdata-archiving/ECHO-Clean-Water-Act 
- [x]  https://github.com/edgi-govdata-archiving/ECHO-by-Zip-Code 
- [x] https://github.com/edgi-govdata-archiving/ECHO-Hazardous-Waste
- [x] https://github.com/edgi-govdata-archiving/Environmental-Enforcement-Watch
- [ ] https://github.com/edgi-govdata-archiving/ECHO-DB-Views
- [ ] https://github.com/edgi-govdata-archiving/ECHO-Watershed

Too in flux at the current moment : ( 
- [ ] https://github.com/edgi-govdata-archiving/ECHO-Cross-Program
- [ ] https://github.com/edgi-govdata-archiving/CD-report
- [ ] https://github.com/edgi-govdata-archiving/ECHO_modules
- [ ] https://github.com/edgi-govdata-archiving/ECHOEPA-to-SQL
- [ ] https://github.com/edgi-govdata-archiving/EEW-Website

Link breaking
- [ ] https://github.com/edgi-govdata-archiving/EEW-Image-Assets
Most every notebook pulls EEW and EDGI images from this repo, so we would need to go through each notebook to update. For now, I've created the main branch and will ask folks to be making this minor update. The master branch will still be there, but we should link instead to main.

Should be archived or deleted? Also a permissions problem. I created issues in both:
- [ ] https://github.com/edgi-govdata-archiving/echo-data
- [ ] https://github.com/edgi-govdata-archiving/echo-ux-testing

---

*2020-09-05: Edited by @Mr0grog to check off completed repos.*

**Comment by Mr0grog** [comment]
> Requires someone with permissions I don't have. I have created main branches in all or most, but I need someone else to approve and set up main as the default.

I can take care of that, @ericnost!

**Comment by Mr0grog** [comment]
@ericnost [EEW_Planning](https://github.com/edgi-govdata-archiving/EEW_Planning) was on your checklist twice — just making sure that was an accidental duplication and that you didn’t mean to type something else the second time it was listed.

**Comment by Mr0grog** [comment]
Also, [edgi-govdata-archiving/ECHO-DB-Views](https://github.com/edgi-govdata-archiving/ECHO-DB-Views) and [edgi-govdata-archiving/ECHO-Watershed](https://github.com/edgi-govdata-archiving/ECHO-Watershed) didn’t have a `main` branch yet so I didn’t touch them. LMK if I should create the branches there.

**Comment by ericnost** [comment]
thank you for the help Rob!

Yes, I think eew_planning was there twice on accident

Ive asked the owners of dbviews and watershed to create branches...

**Comment by Mr0grog** [comment]
Updated the original post with ones that have since been updated:
- https://github.com/edgi-govdata-archiving/ECHO-Watershed
- https://github.com/edgi-govdata-archiving/EEW-Image-Assets
- https://github.com/edgi-govdata-archiving/EEW-Website

I also checked off https://github.com/edgi-govdata-archiving/echo-data since it’s been archived and https://github.com/edgi-govdata-archiving/echo-ux-testing since it appears to have been deleted.

So that leaves 5 repos that never got their default branch changed.

**Comment by Mr0grog** [comment]
Almost there! The only holdout is https://github.com/edgi-govdata-archiving/CD-report
PR at edgi-govdata-archiving/CD-report#21

**Comment by Mr0grog** [comment]
…and we’re done, [CD-report](https://github.com/edgi-govdata-archiving/CD-report) has switched.
