### ISSUE TITLE
Access token param deprecated (labels config)

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/overview#245]
We use [this process](https://github.com/edgi-govdata-archiving/overview/blob/main/repo_guidelines.md#core-issue-label-configuration) to configure our labels, but it looks like one of the query parameters is deprecated:

> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated. If this token is being used by an app you don't have control over, be aware that it may stop working as a result of this deprecation.

> Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.

I haven't looked into this at all, possibly the CLI we use has been updated already to support a new process

**Comment by Mr0grog** [comment]
Seems like that NPM package isn’t maintained. 😞

[“github-label-sync”](https://github.com/Financial-Times/github-label-sync) looks pretty well maintained and very similar in usage. It’s maintained by the Financial Times, so I imagine it’s pretty likely to be around and updated for a long time.

**Comment by Frijol** [comment]
Thanks for checking into this, sounds like we should switch to that
