### ISSUE TITLE
Test IPFS out as storage method for data

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/overview#27]
See related [IPFS archiving issue](https://github.com/ipfs/archives/issues/104), there are multiple steps to work on!

**Comment by dcwalk** [comment]
Kick-off meeting for tonight, should begin testing this week

**Comment by titaniumbones** [comment]
This seems like the most important doc: https://github.com/ipfs/archives/blob/master/tutorials/replicating-large-datasets/mirrors-instructions.md 

BUt also this straight form the source: 

> I’ve just finished writing my update from the 2-week sprint. You can read it here: https://github.com/ipfs/archives/issues/87#issuecomment-275972936 <https://github.com/ipfs/archives/issues/87#issuecomment-275972936>

> Our engineers are cycling onto other work tomorrow but I’ll still be available to coordinate this experiment and to provide some technical support.  I’ve updated https://github.com/ipfs/archives/issues/104 <https://github.com/ipfs/archives/issues/104> to provide an accurate outline.  I’m waiting for info about whether you need to do anything special to capture metrics on performance, etc. Other than that, you’re good to go.

> I’m not sure how Jack’s download is going. I’m fairly certain that he’s finished with the data.gov <http://data.gov/> datasets, but will have to confirm tomorrow.

> If there’s anything you need, please let me know. Also, FYI, I set up a thread in the IPFS forums for data rescuers to get their IPFS questions answered. http://ipfs.trydiscourse.com/t/q-a-helping-data-rescuers-understand-ipfs/78 <http://ipfs.trydiscourse.com/t/q-a-helping-data-rescuers-understand-ipfs/78> If people post questions there, I will personally make sure they get answered.

**Comment by dcwalk** [comment]
~~Did a test using our cluster and I'm having issues running the daemon. Sent a note and waiting to troubleshoot next steps~~
We're good, ready to test!

Dropping this here: https://github.com/ipfs/archives/blob/master/tutorials/replicating-large-datasets/mirrors-instructions.md

**Comment by dcwalk** [comment]
Setting up the daemon--
https://gist.github.com/graffen/e0ff7ca4827959beedb15cf15a9df9d5
https://www.npmjs.com/package/ipfs-daemon or https://github.com/haadcode/ipfs-daemon

**Comment by dcwalk** [comment]
Recommendation from @patcon: re-ticket longer issues when scope changes. Aim to talk about about in Sept 11, meeting.

@jschell42 offered to assist

**Comment by patcon** [comment]
Can anyone add context on the comment about this becoming the "Stanford" collaboration issue? Is there any link to context?

**Comment by dcwalk** [comment]
Prior conversation exists very early in `#archiving_techne`, but mostly happened in person and in emails. 

Here is the IPFS perspective: https://github.com/ipfs/archives/milestone/1 and https://waffle.io/ipfs/archives?milestone=Data.gov%20(aka%20300%20TB%20Challenge)

**Comment by dcwalk** [comment]
Okay, closing this per conversations above, will ticket new bits for upcoming work within the "EDGI" scope
