### ISSUE TITLE
Script improvement to webpage version tracking workflow

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/overview#28]
We need a tool to substantially reduce the manual labor of iinputting & evaluating changes to the web pages we're monitoring.

**Comment by judepark** [comment]
Have anyone checked out piwik? http://developer.piwik.org/guides/tracking-javascript-guide or https://github.com/ruipgil/scraperjs

**Comment by dcwalk** [comment]
I've used Piwik on projects for analytics, I'm not sure I see a fit but I wasn't in the group discussion. I think some of those conversations are in `#guerilla-archiving` if you are able to join in @judepark ?

**Comment by jpmckinney** [comment]
What is this issue about? It has no description. Is it related to https://github.com/edgi-govdata-archiving/version-tracking-ui ?

**Comment by titaniumbones** [comment]
Yes @jpmckkinney, https://github.com/edgi-govdata-archiving/version-tracking-ui resolves this issue, thank you!
