### ISSUE TITLE
Investigate/add in Webrecorder or brozzler info

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/overview#3]
There have been a number of pointers to [webrecorder.io](https://webrecorder.io/) and the IA's [brozzler](https://github.com/internetarchive/brozzler) tool. We should investigate & figure outuse cases, then point to them from here.

**Comment by dcwalk** [comment]
I'm going to close this as won't do, as the scope of this question isn't a fit with the current way we are orchestrating projects. Would assume questions about crawlers to take place in the ambit of Data Together (https://github.com/datatogether/roadmap/issues), if someone thinks this should be revisited let me know!
