### ISSUE TITLE
Incorporate Feedback from last couple DataRescue events

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/overview#30]
Feedback from Philly:
> For future Hackathons:
> * Use the EDGI slack team for all the hackathons.
> * set up a Slack auto-invite button on an EDGI website or the hackathon sites, so people can add themselves to the slack team
> * Encourage the hackathon organizers to use the EDGI github org by default
>   * Makes it easy to add users, manage access, etc.
>   * Let hackathon organizers create repositories within the GitHub org
> * Encourage “Seed and Sort” people to make videos explaining how to use 
>    *  the nominator tool
>    * the guides on google docs 
> * Encourage the tools people or the baggers to create a video on how to run a web crawler and record provenance info

Feedback from Chicago:
> Some hot take/aways:
> * If you plan to scrape for further URLs at the locations we found
     and/or elsewhere, and if someone in the room has a modicum of Python
     experience, Scrapy proved to be a effective and lightweight tool:
     https://doc.scrapy.org/en/1.3/intro/tutorial.html
> * If you too plan to use Webrecorder at an event, I recommend checking
     in first ... in
     order to make sure that the load can be handled and balanced. We
     experienced some service outages that I worry were caused by the
     load I was putting on their proxy server.
> * NASA is a relatively untapped resource! We really only got far
     enough in our time to get a quick sense of the scale of available
     and highly accessible resources here in our short time. If future
     events can focus as much as Toronto did on EPA and Philly on NOAA,
     this would make for an important (and fun!) target.

**Comment by geppy** [comment]
> Encourage the tools people or the baggers to create a video on how to run a web crawler and record provenance info

I'm in favor of automated provenance metadata.  As far as how to encode that, my first thought would be [PROV (W3C standard)](https://www.w3.org/TR/prov-overview/).  If that sounds worth investigating, it may be worth talking to the [dokieli](http://dokie.li/) community about their experiences with it.  It may also be worth talking to the members of the old PROV WG and of [the Provenance IG](http://www.w3.org/2005/Incubator/prov/XGR-prov/).  Then again, it may be worth simply adopting PROV in short order (while consulting relevant experts) to avoid losing that information forever (by virtue of not having a solution in place).

**Comment by dcwalk** [comment]
@geppy I'm a little confused about how PROV works with WARC (or if it does?) We've had the comment come up again RE: automating parts of the metadata/provenance information.

Pinging @emilymae who might have experience with PROV?

**Comment by dcwalk** [comment]
Also, gonna bust that out into an issue as it was raised again at events (#33)

**Comment by dcwalk** [comment]
Feedback from A2: https://gist.github.com/dcwalk/71791ea724395712ff4e572ed57fb0a5

**Comment by emilymae** [comment]
when you're talking about provenance, what sort of metadata / provenance info do you mean exactly? Are you talking about crawlers that generate WARCs or not?

**Comment by emilymae** [comment]
I know the DataONE folks have developed the PROVOne data model extending PROV for scientific workflows (see here: http://vcvcomputing.com/provone/provone.html), but not sure how you would implement something like that for crawlers.

**Comment by dcwalk** [comment]
Thanks @emilymae 😀

**Comment by dcwalk** [comment]
We've addressed most of the points from the first two events we can. Metadata generation is something that is being addressed in the new pipeline app for in-person (and soon remote) events :)

A2 feedback is touched on there and has also been brought forward into NYC event planning. Finally we have an issue in the workflow rep [datarefugephilly/workflow#24](https://github.com/datarefugephilly/workflow/issues/24).

Closing this for now! Please re-open if you feel this wasn't addressed adequately.
