### ISSUE TITLE
Implement solution for managing all workflow tasks at in-person events

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/overview#31]
Based on feedback at the Ann Arbor event, there are many issues around the current spreadsheet task management workflow, to briefly summarize:

- too many people in the sheet causes it to perform slowly
- too many ranges have to be unprotected for work, leading to concerns of missing data, duplication, destruction of data
- many people unfamiliar/uncomfortable with UI (e.g., using filters)
- comments about overall usability (hard to see all relevant, and only relevant, data)

In A2 wrap up/debrief, people mentioned looking at project management tools to handle workflow (examples mentioned are [Phabricator](https://www.phacility.com/phabricator/) and [Jira](https://www.atlassian.com/software/jira)... though it was acknowledged that there has to be the right balance between using powerful tools like this and maintaining as low a barrier of entry as possible.

**Comment by jpmckinney** [comment]
Can a description be added to this issue?

**Comment by dcwalk** [comment]
Yes, edited!

**Comment by dcwalk** [comment]
We have a [Pipeline app](https://harvest-pipeline.herokuapp.com/)! 

My wording was vague ("implement?1" 😕  ... implementation ongoing), but I'm gonna close this as issues for improvement are being added to the pipeline repository. 

We've moved toward tagging, grouping urls, etc... that address this original concerns _and_ will be able to allow people to be involved remotely after this weekend.
