### ISSUE TITLE
Pull down baseline for Website Monitoring service

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/overview#39]
Need to set up the cluster to begin monitoring changes

**Comment by titaniumbones** [comment]
data is here: https://mega.nz/#F!xocXQSwZ!5-g4Hugx_cKgQb0IyxDjwQ

do we have URL's for scinet docs? 

@atesgoral @sonalranjit I forget who exactly was working w dawn on the scinet cluster stuff before. If we can get this data onto the cluster & expose it to the web before Saturday... that would be a Really Good Thing.

**Comment by dcwalk** [comment]
"Large transfers of data to or from SciNet can also be done from the datamover1 and datamover2 nodes (these nodes are also used by Globus behind the scenes). From any of the interactive SciNet nodes, one can ssh to datamover1 or datamover2. These machines have the fastest network connection to the outside world (by a factor of 10; a 10Gb/s link as vs 1Gb/s)"
https://wiki.scinet.utoronto.ca/

**Comment by dcwalk** [comment]
No one was @titaniumbones, we can't provide this access. @atesgoral and @sonalranjit are on our VM, but don't have cluster access

**Comment by titaniumbones** [comment]
Ok. Thx. 

On February 1, 2017 5:59:14 PM EST, dcwalk <notifications@github.com> wrote:
>No one was @titaniumbones, we can't provide this access. @atesgoral and
>@sonalranjit are on our VM, but don't have cluster access
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/edgi-govdata-archiving/overview/issues/39#issuecomment-276810891

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dcwalk** [comment]
This was done!

We have a few that didn't dld, looks like they didn't decrypt, gonna QA to ensure!

**Comment by dcwalk** [comment]
Closing this as the Website Monitoring baseline was dlded, initial set up is happening on Google Cloud infra.
