### ISSUE TITLE
Broad "Issues to Consider" Document

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/overview#40]
Move towards a substtantive/broad ["Issues to consider"](https://hackmd.io/OwIwLApgrAJgbATgLQEMDMCJLCuAzJBAJjywWAjzBgQGMEAGOADiA===) document.

**Comment by dcwalk** [comment]
Some wonderful resources from @emilymae's talk:
- https://tspace-library-utoronto-ca.myaccess.library.utoronto.ca/handle/1807/74866
- http://www.researchobject.org/ 

Lots to think about RE: provenance and use

**Comment by dcwalk** [comment]
LOCKSS principles: https://www.lockss.org/about/principles/

**Comment by dcwalk** [comment]
Hey @titaniumbones cycling back on this, I think we might wind up moving away from generating this "issues to consider" doc, but instead pull some of this into the Post Mortem (#110) and also see what speaks to DataTogether still? #144 

I'll close this issue within a week unless I hear otherwise!

**Comment by dcwalk** [comment]
It was a long week 😓 , closing!
