### ISSUE TITLE
Recommend GH Issues to Event Organizers

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/overview#41]
One outcome from NYC was the sense that we didn't have a good mechanism to collect and act on participant insights about event process. The [next-steps](https://github.com/edgi-govdata-archiving/DataRescueNYC/blob/master/next-steps.md) group recommended using Github Issues in a **lean, event-specific repositoriy** such as [DataRescueNYC](https://github.com/edgi-govdata-archiving/DataRescueNYC) for such issues.

**Comment by titaniumbones** [comment]
Alternatively, we could make an "event-issues" repo to collect all reports, and allow participants to build on each others' experience. Not sure which is better.

**Comment by dcwalk** [comment]
I think we want the context of each event baked into feedback? Alternatively having people post issues where the workflow process lives might be better than rolling a new repo?

**Comment by dcwalk** [comment]
Closing this as stale as our event process before/after has shifted significantly (and I expect will do so again in the next weeks)
