### ISSUE TITLE
Apply for Gogol SoC, deadline Feb 9, 12:00 EST

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/overview#42]
We should get Summer of code students to work on this project! Here's what we stil lneed to do to make this happen:

- [x] Write application guidelines for students (1500 chars, copy from PL?)
- [x] create "Ideas" webpage where we describe possible projects; add link to application
   - [x] should include link to the Archivers public slack invite & instructions to joing the #gsoc-apply channel; 
- [x] add "long" & "short" descriptions of edgi 
- [x] create webpage with instructions to join our Dev chat, mailing list (can we add this to contact?)
- [x] Org Profile
  - [x] Why does your org want to participate in Google Summer of Code?
  - [x] How many potential mentors have agreed to mentor this year?
  - [x] How will you keep mentors engaged with their students?
  - [x] How will you help your students stay on schedule to complete their projects?
  - [x] How will you get your students involved in your community during GSoC?
  - [x] How will you keep students involved with your community after GSoC?
  - [x] Has your org been accepted as a mentor org in Google Summer of Code before?
  - [x] What year was your project started?

**Comment by dcwalk** [comment]
Here is a high level overview: https://summerofcode.withgoogle.com/how-it-works/

**Comment by dcwalk** [comment]
We release our material under an "[OSI-approved license](https://opensource.org/licenses)"!

**Comment by dcwalk** [comment]
@titaniumbones I can't resolve that link, I think it is tied to each individual log in? I think this is a great idea and I hope we can do it :)

**Comment by titaniumbones** [comment]
I **could** change the title but I'm gonna leave it up for a while.

**Comment by titaniumbones** [comment]
updated to public link.  All assignees are also tagged as adminsin the application  so you should have access to it.

**Comment by titaniumbones** [comment]
Did some work on this; we've now done almost everything but the hard parts :-). Updated bug description w/ todo.

**Comment by dcwalk** [comment]
~~We need something up on the website as well, or did I read that wrong?~~ nvm, saw you indicated 'page' above

**Comment by dcwalk** [comment]
Application is completed! There are a couple task related that I'm going to bust out into a new issue :) Congrats @titaniumbones 🎉
