### ISSUE TITLE
Develop Event Training Protocol

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/overview#47]
Thinking about how to make this project sustainable: we need to find effective ways to train people to run events when the old crew (b5, dallan, MAT, etc) are not around.  Some ideas include:

- [x] pipeline walkthrough screencast
~~- up-to-date docs~~
~~- [ ]~~

(edit: _@dcwalk added:
- [x] review feedback from NYC event
- [x] update workflow docs to reflect Archivers App (in progress: `#dev-eventdocs` and https://github.com/datarefuge/workflow)
- [x] reduce duplication across harvestor-tools and workflow

**Comment by dcwalk** [comment]
Renamed, I agree we need to act on this.

**Comment by danielballan** [comment]
As I was talking through the process ~10 times at our designated "Onboarding Bench," it occurred to me that a video version of this would be a good idea.

**Comment by dcwalk** [comment]
Yeah @danielballan we need to dld yr brain, ooooooor have you do a screencast

**Comment by danielballan** [comment]
Hehe. I'll do a screencast. I've seen enough episodes of Westworld and Dollhouse to be wary of "brain downloads."

**Comment by dcwalk** [comment]
I just want to flag here that it is critical to address the feedback from the NYC event.

@danielballan would it make sense to share a skeleton of a screencast outline or something for us to make sure we are hitting the big notes?

**Comment by danielballan** [comment]
Yep. In fact I thought I'd just try talking through it so we can all have something to criticize. Stand by....

**Comment by danielballan** [comment]
Draft 1: https://youtu.be/6QWbtvqTQK0

I start off a little stilted but I warm up as it goes. :- )

I assume I will be redoing this *at least* once more before this weekend so don't hold back your suggestions.

**Comment by dcwalk** [comment]
@sharlychan ^^

**Comment by dcwalk** [comment]
Amazing @danielballan :)) 
I have very few comments, you have an excellent screen cast voice!

1. We should not use an Ann Arbour or previously researched one
2. (But perhaps showing an example of a well-researched one would be awesome?)
3. Can we link to the harvestor tools app?
4. I think we need a bit more discussion over harvesting, but maybe we split that into a second video?
We got a lot of feedback around using the tools and wanting an example

**Comment by danielballan** [comment]
1/2. Agree. I'll find a "clean" example and a near-finished one to show. If anyone knows of a particular good one, please let me know.
3. Just to be sure -- you mean the harvester tools github repo?
4. I think it would take about 2 more minutes to go through actually downloading the Zip Starter, showing its layout, putting in some dummy content, and uploading it. Probably worth doing.

I'll wait at least a day for more feedback before re-recording.

**Comment by dcwalk** [comment]
3. yeah I mean the github repo!

**Comment by dcwalk** [comment]
@danielballan just pinging here on the status of that screencast. With recent changes to the archivers app do we want to make adjustments?

Maybe we work this into the FAQ for the app?

**Comment by titaniumbones** [comment]
Videos were a high-priority request coming out of SF Bay -- we should
have one for hte Chrome extension too, if possible.

**Comment by dcwalk** [comment]
Broke off a bite-sized issue: #73

**Comment by dcwalk** [comment]
I'm going to close this a complete(ish) for now-- we have much improved documentation for events, with videos, app FAQ, and training process for event organizers. There is definitely room for improvement but I think we need to see changes to events in the coming weeks to identify further areas for improvement.
