### ISSUE TITLE
Revamp Event Documentation

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/overview#49]
2017/02/20 Update: We are almost there... but are working with DataRefuge to finalize and collectively establish the event description. I'm going to close this for now and open a new issue to cover todos coming out of that collaboration.

Based on slack conversations on NY event debrief, @ebarry will lead a thorough review and reduce of all event materials. Wanted to throw an issue up so others would be aware that the project is ongoing

Per conversation on `#dev-eventdocs` these are my sense of the todos--
- [x] Provide 'one-pager' for events with KEY CONTACTS
- [x] Streamline/reorganize Event Toolkit
  - [x] Trim out of date docs
  - [x] Add in new graphics/printables
  - [x] Move guides to new [tech guides](https://github.com/edgi-govdata-archiving/guides) repo
- [x] Create 'template' repo for events to fork
- [ ] Update Event Toolkit Website
  - [x] Track overview
  - [ ] Checklist
- [x] Update Overview Repo

Current documentation:
- GH [github overview](https://github.com/edgi-govdata-archiving/overview) **checklist, event tech recommendations**
- GH [DataRescue workflow](https://github.com/datarefuge/workflow) our forked [workflow](https://github.com/edgi-govdata-archiving/workflow) **day-of role descriptions, advance work**
- WEB [event toolkit](https://envirodatagov.org/event-toolkit/) **planning materials, technical guides**
- WEB [agency primers](https://envirodatagov.org/agency-forecasts/) **day-of seeding guides**
- [DataRescue Webinar](https://bluejeans.com/playback/s/g1lFJHH06tvL5evFoKe2lFbPBzU7au7WGA2YyAmDFcoexxskOrqavRIYTNhMmNos)
- [DataRescuePhilly Toolkit](http://www.ppehlab.org/datarescue-philly-toolkit)
- [DataRefuge FAQ](http://www.ppehlab.org/datarefugefaqs)

Important Links/Resources:
- [archivers.slack.com](https://archivers.slack.com)
- GH [github organization](https://github.com/edgi-govdata-archiving/)
- WEB [contact (onboarding to slack/`#dev`)](https://envirodatagov.org/contact/)
- WEB [contributor guidelines](https://github.com/edgi-govdata-archiving/overview/blob/master/CONTRIBUTING.md) for developers
- WEB [code of conduct](https://github.com/edgi-govdata-archiving/overview/blob/master/CONDUCT.md) for online EDGI spaces

Event repositories:
- [DataRescueNYC](https://github.com/edgi-govdata-archiving/DataRescueNYC)
- [DataRescueSFBay](https://github.com/DataRescueSFBay/DataRescueSFBay-Event)
- [DataRescueBoston](https://github.com/datarescue-boston)
- [DataRescue PDX](https://github.com/daniellecrobinson/Data-Rescue-PDX)

**Comment by dcwalk** [comment]
Related issue coming out of NYC: https://github.com/edgi-govdata-archiving/overview/issues/47

**Comment by dcwalk** [comment]
Before we head too far on the guide creation track, I want to make sure the work we are talking about here (https://github.com/edgi-govdata-archiving/guides/issues) aligns with a documentation revamp.

**Comment by dcwalk** [comment]
~Also want to flag this repo as related: https://github.com/edgi-govdata-archiving/agency-primers~
EDIT: we deleted this for now

**Comment by titaniumbones** [comment]
I just did this (have posted it about 3 places now b/c I am just catching up on all my gh notifications): https://github.com/edgi-govdata-archiving/workflow/tree/WIP-pipeline-refactor would love it if @ebarry can include this in the review.

**Comment by dcwalk** [comment]
Personal aspirational link: "Writing Great Documentation" https://byrslf.co/writing-great-documentation-44d90367115a#.nryyloktb

**Comment by dcwalk** [comment]
Request on EDGI side in terms of what is needed for event toolkit doc here:
> 1) where the primers are, what they are for, and how to pick on to work on.  who to talk to about this.  
> 2) how to get chrome extension,  where the seedlist is, filtering issues, who to contact on this,   plus link to doc on how the webcrawler works. 
> 3) invite to the github, and app, where the the workflow on the app, and harvesting tools and so on., and who to contact.

**Comment by dcwalk** [comment]
2017/02/20 Update: We are almost there... but are working with DataRefuge to finalize and collectively establish the event description. I'm going to close this for now and open a new issue to cover todos coming out of that collaboration.
