### ISSUE TITLE
Set up Mailing Lists for events and alumni

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/overview#53]
Recent events have set up a mailing list for planning and we anticipate more doing so. Thinking long term-- we don't want to have a bunch of scattered lists we are trying to maintain in multiple places.

Also, we want to support email but move to having most of our conversations on slack.

To mark this closed:
- [ ] make `lists.envirodatagov.org` to a place to sign up for mailinglists (investigate Mailman)
- [ ] Get multiple people set up as admin, moderators
- [ ] Establish protocol for: folding temporary lists into a larger one (e.g. AdaCamp style having an "alumni" list for people?), code of conduct, moderation
- [ ] Create list for upcoming event

**Comment by dcwalk** [comment]
Also: mailman and configuring mailman correctly are not my favourite things. If someone has an AMAZING BETTER OPTION please share!

**Comment by mhucka** [comment]
Not sure if you know, but you can have a closed Google forum/mailing list. I've personally switched all my projects away from mailman lists to Google. Maybe that's an option?

**Comment by dcwalk** [comment]
The issue we want to deal with is longer-term management of these lists, merging, migrating etc... and folding back side lists into one main list is something that can do (or I've seen it used that way), but we've been recommended off google groups for that reason.

**Comment by mhucka** [comment]
It _is_ possible to populate Google groups with archives of old mail. I've actually done it for several lists, but I have to say it's laborious if you want to preserve chronological order.

**Comment by mistermocha** [comment]
Forgive me for being late to the game... Rather than maintaining a mailman host, why not just set up a google group? It would be simpler and we could work out archiving as needed.

**Comment by dcwalk** [comment]
@mistermocha -- We've been recommended off google groups for long term management by community managers (especially merging/migrating lists)... 

I don't know of any better way than a 'heavier' sol'n where we have more control given the level of ongoing management we are imagining.

**Comment by mistermocha** [comment]
OK, do we plan on hosting a listserv in AWS?

Also @mhucka makes a good-ish point. Migrating a mailing list into a GG is a one-time thing, so if it's a laborious effort that makes life easier, I'm all for it.

**Comment by dcwalk** [comment]
My sense is that it will be an ongoing thing (i.e. migrating/merging lists over time. Maintaining a couple core separate lists)

We have institutionally-support VMs here (Toronto) that we can use. With some degree of support, but not actual list management that we can expect.

**Comment by mistermocha** [comment]
I've been thinking much about this. I'd still like to strongly suggest using something like a google group. Having administered services like this and dealt with the challenge of a mail server, I can say it would be a detraction of our efforts and a poor use of our time. The sooner we file the effort over to a service that has it all figured out, then it will make our lives better.

Google groups are:

- Manageable
- Searchable (even across multiple groups in an org)
- Persistent
- Don't require maintenance
- Free
- Have ready-baked-in access rules
- No special talent is needed to use them
- ... or own them

What examples can do we have for migrating/merging lists? And if we have a use case that requires migrating or merging a list, what would that be? I'd presume that the conditions that make us think GG is not feasible would not necessarily be simple or tenable in a Mailman sever, and then we would still have to maintain such a host.

**Comment by dcwalk** [comment]
@ebarry -- could you add some of your thoughts about managing multiple google groups?
I've only managed a few at a smaller scale.

**Comment by dcwalk** [comment]
An inspirational link for tech movement building: http://www.progcode.co/

**Comment by dcwalk** [comment]
Marking this stalled while we pause and investigate WHAT our communication needs are ☺️

**Comment by dcwalk** [comment]
We wound up going ahead with a single mailing list. Closing as wont do, but we got somewhere similar
