### ISSUE TITLE
Website Tracking Dev Check-In

### ISSUE THREAD

**Issue by trinberg** [edgi-govdata-archiving/overview#54]
As discussed, we wanted to set up a time to chat about the Website Tracking project before the SF Event (Sat. 2/11). On the agenda:
1) Briefly discuss progress
2) Compile technical questions for PageFreezer
3) Update @titaniumbones on the state of the pagefreezer-cli project and outline achievable goals for the SF event, assuming we're able to get a group of coders in a room.

Even if you couldn't make the first standup meeting, please feel free to join. Let us know what your availability is and we'll schedule a time by Wednesday evening: http://doodle.com/poll/qhrev79mg3k7gd9k **Note: All times are EST!**
We'll send out a zoom/hangout link then.

**Comment by ambergman** [comment]
Looks like not too many people were able to do the poll but, to account for work hours, @trinberg, @titaniumbones, and I will be having a quick meeting at **8pm EST today** to discuss the state of the pagefreezer-cli project and compile technical questions for PageFreezer. **Here's a link to the Zoom meeting: https://zoom.us/j/934485111**

If possible, we'll try to move our quick conversation into issues to file in the [pagefreezer-cli milestone](https://github.com/edgi-govdata-archiving/pagefreezer-cli/milestone/1) Dan made after our last meeting.

@agillette @allanpichardo @WestleyArgentum @danielballan @lh00000000 @StephenAlanBuckley @stuartlynn - We hope you can join

**Comment by stuartlynn** [comment]
Will be there

**Comment by lh00000000** [comment]
sorry i didn't get to the poll in time! i think i can make it tonight though

**Comment by dcwalk** [comment]
This happened!
