### ISSUE TITLE
Review README changes

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/overview#6]
I just committed them to master (gaah!) instead of submitting a PR. Nonetheless it would be good if you checked them over.  There are a couple of italicized sections that I'm hoping you can fill in; in general the language may need to be revised, too.

**Comment by dcwalk** [comment]
I think as a first pass this has been completed. 

We should revisit after the next round of events if this can be improved, otherwise individual issues can address the elements we should work on
