### ISSUE TITLE
Perform Accessibility Audit

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/overview#63]
Split off from a discussion in #50

**Comment by dcwalk** [comment]
I'm going to mark this as stale/won't do as I think this was a legacy from when we were using this repo closer to Archivers, it would make sense to address [i18n](https://en.wikipedia.org/wiki/Internationalization_and_localization) and [a11y](http://a11yproject.com/) in issues closer to the codebases and projects they are applied do.

Feel free to reopen if you disagree and think we want a meta issue here
