### ISSUE TITLE
Kick-start development on Website Monitoring project

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/overview#65]
Coming out of our [Feb 14 Standup](https://hackmd.io/EYDgpg7ArAnDIFoAMUDGBmBAWd7gIEMCBGAEwVJHVQCYIQAzSiMIA===#), @ambergman and @titaniumbones are looking to kickstart development for the Website Monitoring project.

TODOs to mark this complete:
- [x] established project management structure (Matt | @titaniumbones Tech Contact; Andrew | @ambergman l Tracking Team Contact)
  - Conversations in `#dev-webmonitoring` slack channel
  - Github issues in core repository, emphasize tagging people 
  - Use weekly standup to sync up on projects
- [x] established 'landing' repo for core docs (e.g., ROADMAP, INTERFACE SPECs)
  - (renamed) https://github.com/edgi-govdata-archiving/pagefreezer-cli
- [x] preliminary Architecture spec (with picture) @titaniumbones 
  - A draft of this will land in https://github.com/edgi-govdata-archiving/web-monitoring/issues/5
- [x] preliminary User Interface mockups from Tracking Team @ambergman 
  - This is ongoing and will land in https://github.com/edgi-govdata-archiving/web-monitoring-ui/issues/35)
- [x] github setup (labels, milestones in 'landing repo,' coordinating old repos @dcwalk
- ~~[ ] functional [user story](https://www.scrumalliance.org/community/articles/2013/september/agile-user-stories) for each component? ;)~~

Current work on the Website Monitoring Project is spread out over:
**New Toolchain**
https://github.com/edgi-govdata-archiving/pagefreezer-cli
https://github.com/edgi-govdata-archiving/filtration
  - issues for what this system needs to look like
https://github.com/edgi-govdata-archiving/differ
  - Service to do the diffing
https://github.com/edgi-govdata-archiving/webdiff-ui
  - UI development

**Old Toolchain**
https://github.com/edgi-govdata-archiving/version-tracking-ui
https://github.com/edgi-govdata-archiving/versionista-outputter

**Comment by Paradoxis** [comment]
Just some thoughts: What if you actually use GitHub for this; you could just scrape a website every hour, overwrite all previously scraped pages, and commit all changes to a repository.

That way you instantly get a side-by-side difference of all changed (or even removed all together) web pages, and it mitigates all issues of having to maintain a custom server with a database, you can even add webhooks to each commit and get instant updates if anything changes (think of push notifications, broadcasts, slack messages, etc).

**Comment by chaoticsmol** [comment]
Looks like we're still inviting some user stories for this, but is there anyone who can provide at least a general overview for what this project's motivation is and what we hope to achieve with it?

**Comment by chaoticsmol** [comment]
Although there has not yet been a detailed conversation about what exactly this tool is going to be expected to do, I figured I'd get started on something that I imagine ought to be a good approach. Check out [the repository that I've created](https://github.com/zsck/miru) if you'd like to keep up with the development and start contributing user stories as issues.

Here's a simple outline of the plan I'm acting on to get started. None of this is final, so whenever some information comes in about how this tool should look, I'm happy to adjust this.

1. Show some basic information about the project in a couple of pages.
2. Build registration features for archivers (regular users) and admins ("lieutenants").
3. Build report feature that users can inform us of sites that need monitoring.
4. Build an admin portal that can be used to:
    1. See and approve/reject reports (see step 3) of new sites to have monitored.
    2. See what sites are already being monitored.
    3. See a stream of changes detected on monitored websites.

I've got a few ideas for future features in mind as well, but for now this is the basic idea. I'm going to expand on these in the repository's issues. Questions and feedback are very welcome!

**Comment by dcwalk** [comment]
Hey @zsck this is awesome :)) I had a chat with @titaniumbones this morning about how to move this forward (and should have updated this issue. Poor form on my part).

We have had some preliminary work done (spread out over a few repos, and I think languages :/). We are shifting off of the previous tool used for monitoring onto using Pagefreezer. My understanding is that the goal is to do full crawls of certain domains, but your point under admin portal RE: nominating to monitor is suuuper interesting and I think should be part of the conversation 😄 .

Anyway, the outcome of my chat this morning is that @titaniumbones will spend some time _tomorrow_ creating a [ROADMAP](https://github.com/edgi-govdata-archiving/pagefreezer-cli/blob/master/ROADMAP.md) from the [PROPOSALs](https://github.com/edgi-govdata-archiving/pagefreezer-cli/blob/master/PROPOSALS.md) and existing work.

We are aiming to have a separate call **MON/TUES** to discuss how to approach this work based on this work. So basically: By the standup there will be much clearer way to work on this.

I've done a scan and put all (I think 😓 ) of the repos where people have built out some prototype component for the project already in the top comment, in particular this one feels aligned with your admin portal: https://github.com/edgi-govdata-archiving/webdiff-ui

Sorry for our poor organization!

**Comment by dcwalk** [comment]
Updated the issue with the outcomes of a project management check in! We will do some wrangling starting tomorrow and expect to check in on this at the Stand Up

**Comment by chaoticsmol** [comment]
I've been trying to keep an eye on everything that's been going on wrt discussion about this subject. I hadn't realized that PageFreezer is actually more in line with what we're looking to move _into_- I thought we were trying to move _away_ from it. My mistake!

I'd like to continue building the prototype of miru out and, when it's ready, demo its capabilities to anyone who might be interested in this monitoring project as a whole. I think there are some good ideas in miru that we could get a lot out of, but it will be hard to demonstrate that without something to show for it.

**Comment by dcwalk** [comment]
@zsck -- I agree that there are a lot of interesting ideas in your prototype. Happy for you to continue in the way that you think will be most rewarding. My sense is we'll be doing a better job at being in communicative around this and there will be an update tonight. Hope to have a convo about it all if you are able to attend to sync up!

**Comment by chaoticsmol** [comment]
Absolutely, @dcwalk! I look forward to it. 👍

**Comment by dcwalk** [comment]
Closing this as stale/complete-- we've definitely started :))
