### ISSUE TITLE
New gh-pages repo for event-specific boilerplate

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/overview#66]
I'd like to set up a gh-pages-only repo to serve as website boilerplate for individual events; event organizers can fork, modify yaml, prune/add as needed, and have an event website ready to go.  Some models  for what such a website needs to include:

- http://datarescuesfbay.org/
- https://datarescue-sea.github.io/DataRescue-SEA/
- https://github.com/edgi-govdata-archiving/DataRescueNYC/

**Comment by dcwalk** [comment]
Hey, this is being addressed as part of #49. I'm working on a template repo from NYC, but I think we need to see how the "Guides" material will fit in. That is where the "Understanding the IA Web Crawler" and "Seeding" docs are moving, I've done a pass to make them current to our process and they are ready for review: https://github.com/edgi-govdata-archiving/guides/issues

Documentation for the process of adding a guide needs to be cleaned up a bit, but the current docs will be easy to have ready for Friday (<30 mins), just would like review of the content while we are going through this step.

**Comment by titaniumbones** [comment]
Excellent. If you're up for it, that's amazing. Maybe stay in touch with @nic on datarefuge (from Seattle) and see if we can get it out to orgnaizers of the 24-5 events...

Do you need help from a designer?

**Comment by titaniumbones** [comment]
(bc if you can use a designer, we should just put out a call on #dev)

**Comment by dcwalk** [comment]
This is working in draft form: 
- https://github.com/edgi-govdata-archiving/DataRescueTEMPLATE/
- https://edgi-govdata-archiving.github.io/DataRescueTEMPLATE/

I'm going to close this issue as completed, event-toolkit stuff will still live in #49 and any specific improvements should go to the Template Repo issues :)
