### ISSUE TITLE
Investigate our ongoing community communication needs

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/overview#72]
Per rich conversation in #53, to emphasize mailinglists is probably too narrow a scope. Will have a community management conversation after the Standup on Feb 21 to identify action items to move this forward.

**Comment by dcwalk** [comment]
After the Feb 21 standup we had a community management and mailing list convo (@mhucka @ebarry @ambergman @trinberg @titaniumbones @mayaad et al.)

The original thought was we wanted to create a centralized place for different event organizers to set up mailing lists:
> we want to support email but move to having most of our conversations on slack.

Based on a range of feedback ( @mistermocha and @mhucka esp. around tech maintenance) we took a step and revisited what our goals were and needs as organizers.

Points from meeting:
- DataRescue events are slack-based
- EDGI and DataRefuge are slack-based communities
- Post-event contact isn't something that has been happening regularly
- Only a few cities (e.g. NYC, Boston, Ann Arbour) are working toward recurring meetings coming out of a DataRescue

Suggestions based on capacity and current situation:
- We honour that we are slack-based, without shifting to mailing lists for most events, those groups that continue organizing can use what service works best for them (e.g. google groups, slack)
- We look into having a "DataRescue" mailing list for infrequent newsletter-style updates
- That "newsletter" is currently implementation agnostic
  - **needs an unsubscribe**
  - @mhucka mentioned looking into slack integrations (slack announcement digests?)

Next steps:
- Proposal for co-governed DataRescue mailing list
  - Any plan will include getting working with completed event organizers to bring those attendees into a list
- Discussion with EDGI Steering Committee RE: event communication

**Comment by mistermocha** [comment]
OK so given the updated requirements, I'm going to suggest Google Groups again to manage a mailing list. How does GG meet our requirements:

- Publicly available (unless we pay for a private account)
- Manageable subscriptions - anyone can self-add or self-delete with relative ease
- Free - no point in wasting dollars that we don't have to spend
- Easy - the interface is pretty clear on how to use
- API available - just in case we need to do a thing

Concerns: I am not aware of any, and would encourage anyone here to list them.

**Comment by dcwalk** [comment]
If we are thinking of it being potentially more "newsletter style" rather than a mailing list, I could see some of the composition features of a email newsletter/marketing service being desirable (I'm thinking tinyletter, constant contact, mailchimp)

**Comment by mistermocha** [comment]
I'm not familiar with tinyletter, but I'm looking at the site and it looks like it might be what we need for just a mailing list. Constant Contact and Mailchimp are more business-y and come with an eventual price tag. For one-way distributions, tinyletter may be the win here.

**Comment by dcwalk** [comment]
This has been happening and strategized as part of a larger effort with the EDGI group, I'm closing this for now as 'investigated' as I think the work will continue in a larger way!
