### ISSUE TITLE
Create video walkthroughs of event tools

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/overview#73]
Repeated requests from event organizers to have a video of :

- [x] Archivers App walkthrough (@danielballan draft 1: https://youtu.be/6QWbtvqTQK0; draft 2: https://www.youtube.com/watch?v=tvSSILnHnpA)
- [x] Chrome Extension walkthrough (@mayaad's training session: https://youtu.be/Ro-f58Cecdg)

Broken off of #47

**Comment by danielballan** [comment]
I can't find the issue where you recently asked about the status of the YouTube video. I will rerecord again before this coming weekend. And maybe at this point we should include a link to the video in the app itself.

**Comment by dcwalk** [comment]
Wonderful! @danielballan 💃 
I believe I pinged you in #47, but having the conversation here makes sense 😊

**Comment by dcwalk** [comment]
Hey @danielballan as far as I'm concerned Draft 2 rocks! 🎉 

We should use this for next weekend.
Can we change the title to "Archivers App Walkthrough" and add a link to the workflow and app in the description?

**Comment by danielballan** [comment]
Great! Done: https://www.youtube.com/watch?v=tvSSILnHnpA

**Comment by dcwalk** [comment]
@mayaad are you or someone on the primers team able to make a primers/chrome tool walkthrough?

**Comment by mayaad** [comment]
@dcwalk I can put it on the to-do list for this weekend. If you need it sooner, let me know. Also, I can ask an organizer if they wouldn't mind me recording a training session. That way we could have something up soon, and then I can try to make a cleaner copy this weekend.

**Comment by dcwalk** [comment]
Recording a training session would be a great initial pass @mayaad! If that is at all possible, please :))

**Comment by dcwalk** [comment]
The Agency Primers and Chrome extension video is up! https://youtu.be/Ro-f58Cecdg

**Comment by dcwalk** [comment]
We've got videos up! I think this is a great first draft, I'll leave iteration improvements to be handled in the workflow documentation repo, etc...
