### ISSUE TITLE
Merge web monitoring repos

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/overview#74]
It's great to see all the web-monitoring related code springing up on github, but it is currently scattered and difficult to track. We should bring all of the active efforts together into one rook so people can work more closely together.  
- [x] rename pagefreezer-cli to a more inclusive name(https://github.com/edgi-govdata-archiving/pagefreezer-cli/issues/23) "EDGI Website Monitoring Software"
- [x] ~move `differ` to renamed EWMS repo~ (https://github.com/edgi-govdata-archiving/differ/issues/3) rename to `web-monitoring-` format
- ~move `webdiff-ui` to renamed EWMS repo~ (https://github.com/edgi-govdata-archiving/webdiff-ui/issues/7)
- ~decprecate (archive) `versionista-outputter` into renamed EWMS repo (when appropriate)~
- [x] move `filtration` issues to renamed EWMS repo 
- [x] deprecate (archive) version-tracking-ui (https://github.com/edgi-govdata-archiving/version-tracking-ui)
- [x] deprecate (archive) `webdiff-ui` (https://github.com/edgi-govdata-archiving/webdiff-ui/i)

**Comment by dcwalk** [comment]
@titaniumbones -- I think we want to leave versionista-outputter and version-tracking-ui separate as they are different codebases doing different things?

My understanding is that version-tracking-ui is no longer in use, if that is the case we should:
- Update project readme/description in repo
- Update project list in overview
...to handle that case

**Comment by dcwalk** [comment]
Sitting on decision about webdiff-ui and the move over to the db for versionista before finalizing the remaining two TODOs

**Comment by dcwalk** [comment]
UPDATE: `webdiff-ui` has been superseded by a react prototype in [`web-monitoring-ui`](https://github.com/edgi-govdata-archiving/web-monitoring-ui)

**Comment by dcwalk** [comment]
Going to mark this as done! The phasing out of `versionista-outputter` is cleanup to do after v0/v1 so not going to sit on this
