### ISSUE TITLE
Revisit GitHub permissions

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/overview#75]
We've grown to the size were I think we need to revisit our permissions structure and check in on whether it is working.

Questions I have:
- Are we creating too much noise for lieutenants?
- Are we creating a bottle neck? Is this too hierarchical? Should we be more distributed? 
- What permissions should they have (currently: `write`)? too low?
- Is there a need for a separate role (e.g. `leads`) with `admin` access?
- What about owners?
- How should we manage project churn, as people get busy and move on?

For reference: 
https://help.github.com/articles/repository-permission-levels-for-an-organization/

cc @edgi-govdata-archiving/lieutenants

**Comment by dcwalk** [comment]
@patcon would welcome your thoughts on this in particular!

**Comment by patcon** [comment]
I'm not actively involved in project dev, so I feel I should eavesdrop on the voicing of pain points before I contribute any thoughts :)

**Comment by dcwalk** [comment]
I can say my pain points:
- I know I have spammed at least one person with unneeded repo notifications (and I tend to be noisy on github)
- I'm feeling like I don't have a strong sense of alignment between who IS and who FEELS like they can merge in PRs (have we centralized power too much?)
- I'm feeling like I don't have a strong sense of who is 'leading' different initiatives
- Based on previous experience, I'm thinking about an expiry date on invites and some permissions just to ensure we don't carry forward permissions are no longer needed.

**Comment by ebarry** [comment]
i might suggest that notifications aren't a problem until people stop
reading the firehose of "all notifications" and then miss the notifications
that are specifically "@ them". This is common on big projects so don't
feel bad. Does anyone know of a fix besides individuals going in and
unwatching repos one-by-one?

--

+1 336-269-1539
@lizbarry <http://twitter.com/lizbarry>

**Comment by patcon** [comment]
Addressing @dcwalk's concerns:

> * I know I have spammed at least one person with unneeded repo notifications (and I tend to be noisy on github)

Great point @ebarry. I hadn't realized that Lieutenants should be hyper-aware from the start that they can and should unwatch repos they don't have a vested stake in.

> * I'm feeling like I don't have a strong sense of alignment between who IS and who FEELS like they can merge in PRs (have we centralized power too much?)

Not that another tool is the right solution, but maybe [PullApprove](https://about.pullapprove.com/) could help with this -- active people "leading" different initiatives are lieutenants (with whom there are a little more expectations), and then there's a lower level of people who are trusted to give a +1 that is understood as a vote of full confidence in a merge (ie. the lieutenant can just click "merge" without reading through, if X number of +1's was given by those trusted folks)

> * Based on previous experience, I'm thinking about an expiry date on invites and some permissions just to ensure we don't carry forward permissions are no longer needed.

PullApprove might help as the "trusted" group is in a yaml file, and you can add/remove people quite easily. Then, if you wanted to "remove" someone, you could open a PR for that removal, and give them a chance to speak up. This seems better than the unilateral removal of privileges from the org admin, where convo or appeal is out-of-band.

Disclaimer: have not admin'd any repos using pullapprove.

**Comment by dcwalk** [comment]
We've updated our GitHub owners and lieutenants, I'm comfortable leaving it at this for now, we may want to revisit the [member privileges](https://github.com/organizations/edgi-govdata-archiving/settings/member_privileges) in the near future, but I see that as post-"future of events" conversations

**Comment by patcon** [comment]
Oh hey, when we revisit this, this might be a helpful thingy -- basically a standard format for saying who's in charge of what files, and a github automation piece that automatically @mentions users/orgs/teams in new issues based on that file

https://github.com/probot/probot work-in-progress github automation bot run by github
https://github.com/bkeepers/owners a standard for saying who owns bits of projects
https://github.com/probot/owners probot plugin for @mentions

EDIT: Protocol https://chromium.googlesource.com/chromium/src/+/master/docs/code_reviews.md
