### ISSUE TITLE
EDGI Website Monitoring Dev Meeting

### ISSUE THREAD

**Issue by ambergman** [edgi-govdata-archiving/overview#81]
We'll be having a meeting today (Friday, March 3) at 8pm EST for everyone interested in the ongoing work developing EDGI's Website Monitoring Software Platform. [Here's the link](https://zoom.us/j/259188871) for the Zoom meeting - please use the #dev-webmonitoring channel on the Archivers Slack or contact me directly with any questions.

Dan Allan (@danielballan), along with @titaniumbones, @Mr0grog, @lightandluck, and myself, will be leading a discussion on the progress in designing the platform's architecture, the code written so far, and the plans for future coordination and code (including combining existing code into three repos: [web-monitoring-processing](https://github.com/edgi-govdata-archiving/web-monitoring-processing), [web-monitoring-db](https://github.com/edgi-govdata-archiving/web-monitoring-db), and [web-monitoring-ui](https://github.com/edgi-govdata-archiving/web-monitoring-ui)). We'll finish by allocating components and modules that can be developed in conjunction with the existing code to everyone interested.

For more details, see the "Monitoring Websites" section of the [Overview repo readme](https://github.com/edgi-govdata-archiving/overview/blob/master/README.md) for a short review and see [this issue](https://github.com/edgi-govdata-archiving/web-monitoring-ui/issues/29) for a summary of some of the discussion about how we've chosen to integrate ongoing efforts.

To everyone who attended the SF event and was interested in the [filtration and categorization work](https://github.com/edgi-govdata-archiving/filtration/issues/1) we discussed ( @abelsouza, @nadesai, @aleatha, @evanbloom, @blakelymcconnell, @aschn, @rahul-x-verma, @vidya, @prabathgu ): I'm sorry for the huge delay in getting in touch. We finally have a sense for how the filtration work fits in to the bigger picture, and, if you're still interested, it would be great to see you at the meeting to finally discuss roles. If any of you have more significant notes from that day, it would be great if you could send them over before the meeting.

To everyone who attended the NY event and was involved in the early-stage code writing and much more ( @KrishnaKulkarni, @trinberg, @stuartlynn, @agillette, @allanpichardo, @WestleyArgentum, @StephenAlanBuckley, @lh00000000 ): We hope you can come too. We're really excited to give you an update and get your feedback on where we're heading and some of our decisions to combine efforts so far.

**Comment by dcwalk** [comment]
This happened! In the future can we post these in the web-monitoring repo @ambergman? It might be easier to have the events live closer to the project
