### ISSUE TITLE
Prep for GSoC

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/overview#83]
We got accepted to Google Summer of Code (aiii!) Lots to do, TODOs in the next few days to mark this issue complete:
- [x] Mentor Guidelines posted DRAFT
- [x] Admin doc for year DRAFT
- [x] Mentor Recruitment callout
- [x] GSoC Student Call I (with @titaniumbones) Mar 08, 8-10am ET 	
   - [x] Update idea descriptions & application process based on call 
- [x] First-timer issues in `archivers.space` and `web-monitoring` (and sundry repos) **ASAP!! IMPORTANT**
- [x] Mentor Call (after Mar 15)
- [x] GSoC Student Call II (with @dcwalk) Mar 24, 8-10pm ET

**Comment by dcwalk** [comment]
Partially addressed in #84

**Comment by mhucka** [comment]
For more ideas of materials and things to say about GSOC, the following might be useful: http://www.nrnb.org/gsoc.html

**Comment by dcwalk** [comment]
Great resource @mhucka, adding to the admin resources :)
