### ISSUE TITLE
Share DataRefuge S3 bucket metadata

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/overview#99]
Is there a way that we can coordinate with Dat Projects Svalbard? Per https://github.com/datproject/svalbard/issues/6:
> I heard there's an S3 bucket being used to store data from DataRefuge hackathons. Not sure if there's metadata available for what they have on there.

**Comment by b5** [comment]
Yes I think there is! I'll reach out to project Svalbard today.

**Comment by dcwalk** [comment]
I'm closing this as a previous potential todo that doesn't reflect current archiving efforts :)
